; generated by PrusaSlicer 2.5.0+win64 on 2022-12-07 at 00:02:52 UTC

; 

; external perimeters extrusion width = 1.00mm
; perimeters extrusion width = 1.00mm
; infill extrusion width = 1.00mm
; solid infill extrusion width = 1.00mm
; top infill extrusion width = 1.00mm
; support material extrusion width = 1.00mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M107
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M140 S60 ; set final bed temp
M104 S150 ; set temporary nozzle temp to prevent oozing during homing and auto bed leveling
G4 S10 ; allow partial nozzle warmup
G28 ; home all axisG1 Z50 F240
G1 X7.6 Y10 F3000
M104 S210 ; set final nozzle temp
M190 S60 ; wait for bed temp to stabilize
M109 S210 ; wait for nozzle temp to stabilize
G1 Z0.28 F240
G92 E0
G1 Y140 E10 F1500 ; prime the nozzle
G1 X4 F5000
G92 E0
M73 P11 R0
G1 Y10 E10 F1200 ; prime the nozzle
G92 E0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.35
;HEIGHT:0.35
;BEFORE_LAYER_CHANGE
G92 E0
;0.35


G1 E-1 F3600
M73 P24 R0
G1 Z.35 F7800
;AFTER_LAYER_CHANGE
;0.35
G1 X82.111 Y92.44
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:0.42
M73 P27 R0
G1 F900
G1 X82.111 Y88.074 E.21913
G1 X84.621 Y88.574 E.12842
G1 X94.559 Y92.44 E.53521
M73 P28 R0
G1 X82.261 Y92.44 E.6172
M73 P29 R0
G1 X81.766 Y92.785 F7800
;TYPE:External perimeter
M73 P31 R0
G1 F900
G1 X81.766 Y87.653 E.25754
G1 X84.718 Y88.241 E.15102
M73 P32 R0
G1 X96.397 Y92.785 E.62895
G1 X81.916 Y92.785 E.72674
M73 P34 R0
G1 X81.957 Y91.803 F7800
M73 P36 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X81.901 Y92.265 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X92.116 Y91.601 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:0.426107
G1 F900
M73 P37 R0
G1 X92.697 Y92.182 E.04196
G1 X92.201 Y92.182 E.02535
G1 X91.576 Y91.557 E.0451
G1 X90.764 Y91.241 E.04453
G1 X91.704 Y92.182 E.06793
G1 X91.208 Y92.182 E.02535
G1 X89.951 Y90.925 E.09076
G1 X89.139 Y90.609 E.04453
G1 X90.711 Y92.182 E.11359
M73 P38 R0
G1 X90.215 Y92.182 E.02535
G1 X88.326 Y90.293 E.13642
G1 X87.514 Y89.977 E.04453
G1 X89.719 Y92.182 E.15925
G1 X89.222 Y92.182 E.02535
M73 P39 R0
G1 X86.701 Y89.661 E.18208
G1 X85.889 Y89.345 E.04453
G1 X88.726 Y92.182 E.20491
M73 P40 R0
G1 X88.23 Y92.182 E.02535
G1 X85.077 Y89.028 E.22774
G1 X84.548 Y88.823 E.02897
M73 P41 R0
G1 X84.331 Y88.78 E.01128
G1 X87.733 Y92.182 E.24571
G1 X87.237 Y92.182 E.02535
M73 P42 R0
G1 X83.712 Y88.656 E.25463
G1 X83.092 Y88.533 E.03228
G1 X86.74 Y92.182 E.26355
G1 X86.244 Y92.182 E.02535
M73 P43 R0
G1 X82.472 Y88.409 E.27246
G1 X82.37 Y88.389 E.00532
M73 P44 R0
G1 X82.37 Y88.804 E.02117
G1 X85.748 Y92.182 E.24399
G1 X85.251 Y92.182 E.02535
M73 P45 R0
G1 X82.37 Y89.3 E.20813
G1 X82.37 Y89.796 E.02535
G1 X84.755 Y92.182 E.17228
G1 X84.259 Y92.182 E.02535
M73 P46 R0
G1 X82.37 Y90.293 E.13643
G1 X82.37 Y90.789 E.02535
G1 X83.762 Y92.182 E.10057
G1 X83.266 Y92.182 E.02535
M73 P47 R0
G1 X82.37 Y91.286 E.06472
G1 X82.37 Y91.782 E.02535
G1 X82.925 Y92.337 E.04008
M106 S255
;LAYER_CHANGE
;Z:0.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;0.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X82.557 Y91.969 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z.85 F7800
;AFTER_LAYER_CHANGE
;0.85
M104 S205 ; set temperature
G1 X82.949 Y91.602
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1
M73 P48 R0
G1 F900
G1 X82.949 Y89.515 E.38731
G1 X84.005 Y89.726 E.19982
G1 X88.83 Y91.602 E.96082
G1 X83.099 Y91.602 E1.06361
M73 P49 R0
G1 X82.056 Y92.495 F7800
;TYPE:External perimeter
M73 P50 R0
G1 F900
G1 X82.056 Y88.427 E.75488
G1 X84.256 Y88.865 E.4162
G1 X93.588 Y92.495 E1.85824
M73 P51 R0
G1 X82.206 Y92.495 E2.11221
M73 P52 R0
G1 X82.237 Y91.511 F7800
M73 P53 R0
G1 E-.7 F3600
;WIPE_START
M73 P54 R0
G1 F6240
G1 X82.187 Y91.975 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X84.623 Y90.258 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:1.01327
G1 F900
G1 X83.547 Y91.335 E.28677
;LAYER_CHANGE
;Z:1.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;1.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X83.914 Y90.967 E-.285
;WIPE_END
G1 E-.015 F3600
M73 P55 R0
G1 Z1.35 F7800
;AFTER_LAYER_CHANGE
;1.35
G1 X83.073 Y91.479
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1.2475
G1 F900
G1 X83.073 Y90.161 E.3124
G1 X83.523 Y90.25 E.10881
G1 X86.682 Y91.479 E.80347
G1 X83.223 Y91.479 E.82002
M73 P56 R0
G1 X82.056 Y92.495 F7800
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X82.056 Y88.922 E.66311
G1 X83.808 Y89.271 E.33156
M73 P57 R0
G1 X92.102 Y92.495 E1.65123
G1 X82.206 Y92.495 E1.83635
M73 P58 R0
G1 X82.221 Y91.509 F7800
;LAYER_CHANGE
;Z:1.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;1.85


M73 P60 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X82.184 Y91.976 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z1.85 F7800
;AFTER_LAYER_CHANGE
;1.85
G1 X82.955 Y91.596
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1.01219
G1 F900
G1 X82.955 Y90.512 E.20401
G1 X83.109 Y90.542 E.02948
M73 P61 R0
G1 X85.821 Y91.596 E.54734
G1 X83.105 Y91.596 E.51086
G1 X82.056 Y92.495 F7800
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X82.056 Y89.416 E.57134
G1 X83.361 Y89.676 E.24692
M73 P62 R0
G1 X90.615 Y92.495 E1.44419
G1 X82.206 Y92.495 E1.56045
M73 P63 R0
G1 X82.2 Y91.505 F7800
;LAYER_CHANGE
;Z:2.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;2.35


M73 P64 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
M73 P65 R0
G1 X82.181 Y91.976 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z2.35 F7800
;AFTER_LAYER_CHANGE
;2.35
G1 X82.056 Y92.495
G1 E1 F2400
G1 F900
G1 X82.056 Y89.911 E.47957
G1 X82.914 Y90.082 E.16228
G1 X89.128 Y92.495 E1.23709
M73 P66 R0
G1 X82.206 Y92.495 E1.28449
G1 X82.17 Y91.502 F7800
M73 P67 R0
G1 X83.34 Y91.379
;TYPE:Perimeter
;WIDTH:1.44654
G1 F900
M73 P68 R0
G1 X83.256 Y91.524 E.04661
G1 X83.088 Y91.524 E.0466
G1 X83.005 Y91.379 E.0466
G1 X83.088 Y91.234 E.04661
G1 X83.256 Y91.234 E.0466
;LAYER_CHANGE
;Z:2.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;2.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X83.088 Y91.234 E-.09175
G1 X83.005 Y91.379 E-.09175
G1 X83.088 Y91.524 E-.09175
G1 X83.106 Y91.524 E-.00975
;WIPE_END
G1 E-.015 F3600
G1 Z2.85 F7800
;AFTER_LAYER_CHANGE
;2.85
G1 X82.056 Y92.495
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X82.056 Y90.404 E.38801
G1 X82.466 Y90.487 E.07758
M73 P69 R0
G1 X87.641 Y92.495 E1.03004
G1 X82.206 Y92.495 E1.00847
M73 P70 R0
G1 X82.123 Y91.497 F7800
G1 X83.046 Y91.614
;TYPE:Perimeter
;WIDTH:0.976091
G1 F900
M73 P71 R0
G1 X82.991 Y91.708 E.01961
G1 X82.883 Y91.708 E.01961
G1 X82.828 Y91.614 E.01961
G1 X82.883 Y91.52 E.01961
G1 X82.991 Y91.52 E.01961
;LAYER_CHANGE
;Z:3.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;3.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X82.883 Y91.52 E-.05952
G1 X82.828 Y91.614 E-.05952
G1 X82.883 Y91.708 E-.05952
G1 X82.991 Y91.708 E-.05952
G1 X83.034 Y91.634 E-.04692
;WIPE_END
G1 E-.015 F3600
G1 Z3.35 F7800
;AFTER_LAYER_CHANGE
;3.35
G1 X82.157 Y92.394
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:1.20243
G1 F900
G1 X82.157 Y91.046 E.30674
G1 X85.629 Y92.394 E.84785
M73 P72 R0
G1 X82.307 Y92.394 E.75627
G1 X83.023 Y92.894 F7800
;LAYER_CHANGE
;Z:3.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;3.85


M73 P73 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X82.25 Y91.877 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z3.85 F7800
;AFTER_LAYER_CHANGE
;3.85
G1 X82.042 Y92.51
G1 E1 F2400
;WIDTH:0.970743
G1 F900
G1 X82.042 Y91.447 E.19068
G1 X84.779 Y92.51 E.52705
G1 X82.192 Y92.51 E.46443
M73 P74 R0
G1 X82.908 Y93.01 F7800
;LAYER_CHANGE
;Z:4.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;4.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X82.119 Y91.995 E-.285
;WIPE_END
G1 E-.015 F3600
M73 P75 R0
G1 Z4.35 F7800
;AFTER_LAYER_CHANGE
;4.35
G1 X82.4 Y92.31
G1 E1 F2400
;WIDTH:1.3708
G1 F900
G1 X82.321 Y92.446 E.04148
G1 X82.163 Y92.446 E.04148
G1 X82.084 Y92.31 E.04148
G1 X82.163 Y92.173 E.04148
G1 X82.321 Y92.173 E.04148
;LAYER_CHANGE
;Z:4.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;4.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X82.163 Y92.173 E-.08656
G1 X82.084 Y92.31 E-.08656
G1 X82.163 Y92.446 E-.08656
G1 X82.209 Y92.446 E-.02531
;WIPE_END
G1 E-.015 F3600
G1 Z4.85 F7800
;AFTER_LAYER_CHANGE
;4.85
G1 X82.116 Y92.541
M73 P76 R0
G1 E1 F2400
;WIDTH:0.957301
G1 F900
G1 X82.063 Y92.633 E.01877
G1 X81.957 Y92.633 E.01877
G1 X81.904 Y92.541 E.01877
G1 X81.957 Y92.449 E.01877
G1 X82.063 Y92.449 E.01877
;LAYER_CHANGE
;Z:5.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;5.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X81.957 Y92.449 E-.05823
G1 X81.904 Y92.541 E-.05823
G1 X81.957 Y92.633 E-.05823
G1 X82.063 Y92.633 E-.05823
G1 X82.111 Y92.551 E-.05207
;WIPE_END
G1 E-.015 F3600
G1 Z5.35 F7800
;AFTER_LAYER_CHANGE
;5.35
G1 X81.884 Y92.773
G1 E1 F2400
G1 F900
G1 X81.831 Y92.865 E.01877
G1 X81.725 Y92.865 E.01877
G1 X81.672 Y92.773 E.01877
G1 X81.725 Y92.681 E.01877
G1 X81.831 Y92.681 E.01877
G1 E-.7 F3600
;WIPE_START
M73 P77 R0
G1 F6240;_WIPE
G1 X81.725 Y92.681 E-.05823
G1 F6240;_WIPE
G1 X81.672 Y92.773 E-.05823
G1 F6240;_WIPE
G1 X81.725 Y92.865 E-.05823
G1 F6240;_WIPE
G1 X81.831 Y92.865 E-.05823
G1 F6240;_WIPE
G1 X81.879 Y92.783 E-.05207
;WIPE_END
G1 E-.015 F3600
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G1 Z7.35 F600 ; Move print head up
G1 X5 Y144 F7800 ; present print
G1 Z75.35 F600 ; Move print head further up
M73 P79 R0
G1 Z108 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84 X Y E ; disable motors
M73 P100 R0
; filament used [mm] = 36.31
; filament used [cm3] = 0.09
; filament used [g] = 0.11
; filament cost = 0.00
; total filament used [g] = 0.11
; total filament cost = 0.00
; estimated printing time (normal mode) = 49s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0\n;{layer_z}\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = ;printer_notes=~/.*PRINTER_VENDOR_KINGROON.*/
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "PLA @KP3S"
; default_print_profile = 0.16mm @KP3S
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.8} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84 X Y E ; disable motors
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 1
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #DDDDDD
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 10
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "PLA @KP3S - Copy"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 5%
; fill_pattern = 3dhoneycomb
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 120%
; first_layer_height = 0.35
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = ;"PLA @KP3S";KP3S
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;{layer_z}
; layer_height = 0.5
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 500
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 500
; machine_max_acceleration_y = 500
; machine_max_acceleration_z = 100
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 10
; machine_max_jerk_e = 5
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.75
; max_print_height = 180
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.1
; min_print_speed = 15
; min_skirt_length = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 1
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = 
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 2
; physical_printer_settings_id = KP3S01
; post_process = 
; print_settings_id = KP3S Custom
; printer_model = KP3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_KINGROON\nPRINTER_MODEL_KP3S\n
; printer_settings_id = KP3S - 1.0mm
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 1
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 60
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM140 S{first_layer_bed_temperature[0]} ; set final bed temp\nM104 S150 ; set temporary nozzle temp to prevent oozing during homing and auto bed leveling\nG4 S10 ; allow partial nozzle warmup\nG28 ; home all axisG1 Z50 F240\nG1 X7.6 Y10 F3000\nM104 S{first_layer_temperature[0]} ; set final nozzle temp\nM190 S{first_layer_bed_temperature[0]} ; wait for bed temp to stabilize\nM109 S{first_layer_temperature[0]} ; wait for nozzle temp to stabilize\nG1 Z0.28 F240\nG92 E0\nG1 Y140 E10 F1500 ; prime the nozzle\nG1 X4 F5000\nG92 E0\nG1 Y10 E10 F1200 ; prime the nozzle\nG92 E0
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 20
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 205
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 12
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
