; generated by PrusaSlicer 2.5.0+win64 on 2022-12-07 at 00:04:59 UTC

; 

; external perimeters extrusion width = 1.00mm
; perimeters extrusion width = 1.00mm
; infill extrusion width = 1.00mm
; solid infill extrusion width = 1.00mm
; top infill extrusion width = 1.00mm
; support material extrusion width = 1.00mm
; first layer extrusion width = 0.42mm

M73 P0 R1
M107
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M140 S60 ; set final bed temp
M104 S150 ; set temporary nozzle temp to prevent oozing during homing and auto bed leveling
G4 S10 ; allow partial nozzle warmup
G28 ; home all axisG1 Z50 F240
G1 X7.6 Y10 F3000
M104 S210 ; set final nozzle temp
M190 S60 ; wait for bed temp to stabilize
M109 S210 ; wait for nozzle temp to stabilize
G1 Z0.28 F240
G92 E0
G1 Y140 E10 F1500 ; prime the nozzle
G1 X4 F5000
G92 E0
M73 P7 R1
G1 Y10 E10 F1200 ; prime the nozzle
G92 E0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.35
;HEIGHT:0.35
;BEFORE_LAYER_CHANGE
G92 E0
;0.35


G1 E-1 F3600
M73 P15 R1
G1 Z.35 F7800
;AFTER_LAYER_CHANGE
;0.35
G1 X78.123 Y92.795
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:0.42
M73 P17 R1
G1 F900
G1 X78.123 Y87.765 E.25241
G1 X85.481 Y89.743 E.38236
G1 X97.31 Y92.795 E.61307
M73 P18 R1
G1 X78.273 Y92.795 E.95536
M73 P19 R1
G1 X77.778 Y93.14 F7800
;TYPE:External perimeter
M73 P20 R1
G1 F900
G1 X77.778 Y87.316 E.29229
G1 X85.57 Y89.41 E.40493
M73 P21 R1
G1 X100.027 Y93.14 E.74928
M73 P22 R1
G1 X77.928 Y93.14 E1.10905
M73 P23 R1
G1 X78.144 Y92.209 F7800
M73 P25 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X77.915 Y92.62 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X94.36 Y92.141 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:0.427999
G1 F900
G1 X94.755 Y92.536 E.02872
G1 X94.256 Y92.536 E.02563
G1 X93.903 Y92.183 E.02563
M73 P26 R0
G1 X93.231 Y92.01 E.03567
G1 X93.757 Y92.536 E.03823
G1 X93.258 Y92.536 E.02563
G1 X92.558 Y91.836 E.05083
G1 X91.886 Y91.663 E.03567
G1 X92.759 Y92.536 E.06343
G1 X92.26 Y92.536 E.02563
G1 X91.213 Y91.489 E.07603
G1 X90.54 Y91.316 E.03567
G1 X91.761 Y92.536 E.08864
G1 X91.262 Y92.536 E.02563
G1 X89.868 Y91.142 E.10124
G1 X89.195 Y90.969 E.03567
M73 P27 R0
G1 X90.763 Y92.536 E.11384
G1 X90.264 Y92.536 E.02563
G1 X88.523 Y90.795 E.12644
G1 X87.85 Y90.622 E.03567
G1 X89.765 Y92.536 E.13904
G1 X89.266 Y92.536 E.02563
G1 X87.178 Y90.448 E.15164
G1 X86.505 Y90.275 E.03567
M73 P28 R0
G1 X88.767 Y92.536 E.16424
G1 X88.268 Y92.536 E.02563
G1 X85.832 Y90.101 E.17684
G1 X85.156 Y89.924 E.03591
G1 X87.769 Y92.536 E.18972
G1 X87.269 Y92.536 E.02563
M73 P29 R0
G1 X84.474 Y89.74 E.20304
G1 X83.791 Y89.557 E.03629
G1 X86.77 Y92.536 E.21636
G1 X86.271 Y92.536 E.02563
M73 P30 R0
G1 X83.108 Y89.373 E.22969
G1 X82.426 Y89.19 E.03629
G1 X85.772 Y92.536 E.24301
G1 X85.273 Y92.536 E.02563
M73 P31 R0
G1 X81.743 Y89.006 E.25633
G1 X81.061 Y88.823 E.03629
G1 X84.774 Y92.536 E.26966
G1 X84.275 Y92.536 E.02563
G1 X80.378 Y88.64 E.28298
M73 P32 R0
G1 X79.696 Y88.456 E.03629
G1 X83.776 Y92.536 E.2963
G1 X83.277 Y92.536 E.02563
M73 P33 R0
G1 X79.013 Y88.273 E.30963
G1 X78.382 Y88.103 E.03358
G1 X78.382 Y88.14 E.00192
G1 X82.778 Y92.536 E.31924
G1 X82.279 Y92.536 E.02563
M73 P34 R0
G1 X78.382 Y88.639 E.283
G1 X78.382 Y89.138 E.02563
G1 X81.78 Y92.536 E.24676
G1 X81.281 Y92.536 E.02563
M73 P35 R0
G1 X78.382 Y89.637 E.21052
G1 X78.382 Y90.136 E.02563
G1 X80.782 Y92.536 E.17428
G1 X80.283 Y92.536 E.02563
G1 X78.382 Y90.635 E.13804
G1 X78.382 Y91.135 E.02563
M73 P36 R0
G1 X79.784 Y92.536 E.10179
G1 X79.285 Y92.536 E.02563
G1 X78.382 Y91.634 E.06555
G1 X78.382 Y92.133 E.02563
G1 X78.941 Y92.691 E.04058
M106 S255
;LAYER_CHANGE
;Z:0.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;0.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X78.573 Y92.324 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z.85 F7800
;AFTER_LAYER_CHANGE
;0.85
M104 S205 ; set temperature
G1 X78.961 Y91.957
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1
M73 P37 R0
G1 F900
G1 X78.961 Y89.14 E.5227
G1 X84.534 Y90.639 E1.07095
G1 X89.645 Y91.957 E.97947
G1 X79.111 Y91.957 E1.95482
M73 P38 R0
G1 X78.068 Y92.85 F7800
;TYPE:External perimeter
M73 P39 R0
G1 F900
G1 X78.068 Y87.976 E.90443
G1 X84.766 Y89.776 E1.28702
G1 X96.679 Y92.85 E2.28308
M73 P40 R0
G1 X78.218 Y92.85 E3.42576
M73 P41 R0
G1 X78.439 Y91.921 F7800
M73 P42 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
M73 P43 R0
G1 X78.202 Y92.33 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X82.646 Y91.689 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:1.00603
G1 F900
G1 X83.335 Y91 E.18216
G1 X82.331 Y90.733 E.19412
G1 X81.776 Y91.288 E.1465
G1 X80.505 Y91.288 E.23745
G1 X81.327 Y90.466 E.21697
G1 X80.322 Y90.2 E.19412
G1 X79.229 Y91.293 E.28894
;LAYER_CHANGE
;Z:1.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;1.35


G1 E-.7 F3600
;WIPE_START
M73 P44 R0
G1 F6240
G1 X79.596 Y90.926 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z1.35 F7800
;AFTER_LAYER_CHANGE
;1.35
G1 X78.961 Y91.957
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1
G1 F900
G1 X78.961 Y89.472 E.4611
G1 X83.69 Y90.743 E.90862
G1 X88.394 Y91.957 E.90167
M73 P45 R0
G1 X79.111 Y91.957 E1.72273
G1 X78.068 Y92.85 F7800
;TYPE:External perimeter
M73 P46 R0
G1 F900
G1 X78.068 Y88.308 E.84283
G1 X83.908 Y89.878 E1.12218
G1 X95.428 Y92.85 E2.20779
M73 P47 R0
G1 X78.218 Y92.85 E3.19367
M73 P48 R0
G1 X78.427 Y91.916 F7800
M73 P49 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X78.201 Y92.33 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X80.338 Y90.119 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:1.17854
M73 P50 R0
G1 F900
G1 X81.506 Y91.288 E.36788
G1 X79.991 Y91.288 E.33736
G1 X79.229 Y90.526 E.23999
;LAYER_CHANGE
;Z:1.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;1.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X79.596 Y90.893 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z1.85 F7800
;AFTER_LAYER_CHANGE
;1.85
G1 X78.961 Y91.957
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1
G1 F900
M73 P51 R0
G1 X78.961 Y89.804 E.3995
G1 X82.832 Y90.845 E.74378
G1 X87.144 Y91.957 E.82638
G1 X79.111 Y91.957 E1.49063
G1 X78.068 Y92.85 F7800
;TYPE:External perimeter
M73 P52 R0
G1 F900
G1 X78.068 Y88.64 E.78123
G1 X83.05 Y89.979 E.95734
M73 P53 R0
G1 X94.178 Y92.85 E2.1325
G1 X78.218 Y92.85 E2.96157
M73 P54 R0
G1 X78.411 Y91.91 F7800
M73 P55 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X78.2 Y92.33 E-.285
;WIPE_END
G1 E-.015 F3600
M73 P56 R0
G1 X80.909 Y90.603 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:1.15946
G1 F900
G1 X79.822 Y91.689 E.33607
;LAYER_CHANGE
;Z:2.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;2.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X80.19 Y91.322 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z2.35 F7800
;AFTER_LAYER_CHANGE
;2.35
G1 X79.133 Y91.785
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1.34386
G1 F900
G1 X79.133 Y90.36 E.36622
G1 X81.916 Y91.109 E.74082
G1 X84.538 Y91.785 E.69611
M73 P57 R0
G1 X79.283 Y91.785 E1.3509
G1 X78.068 Y92.85 F7800
;TYPE:External perimeter
;WIDTH:1
G1 F900
M73 P58 R0
G1 X78.068 Y88.972 E.71963
G1 X82.192 Y90.081 E.7925
G1 X92.927 Y92.85 E2.05721
G1 X78.218 Y92.85 E2.72948
M73 P59 R0
G1 X78.389 Y91.903 F7800
;LAYER_CHANGE
;Z:2.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;2.85


M73 P60 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
M73 P61 R0
G1 X78.198 Y92.33 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z2.85 F7800
;AFTER_LAYER_CHANGE
;2.85
G1 X79.061 Y91.857
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1.19981
G1 F900
G1 X79.061 Y90.598 E.28587
G1 X83.855 Y91.857 E1.1257
G1 X79.211 Y91.857 E1.05474
G1 X78.068 Y92.85 F7800
;TYPE:External perimeter
;WIDTH:1
M73 P62 R0
G1 F900
G1 X78.068 Y89.304 E.65803
G1 X81.335 Y90.182 E.62766
G1 X91.676 Y92.85 E1.98193
M73 P63 R0
G1 X78.218 Y92.85 E2.49739
G1 X78.359 Y91.893 F7800
;LAYER_CHANGE
;Z:3.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;3.35


M73 P65 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X78.196 Y92.33 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z3.35 F7800
;AFTER_LAYER_CHANGE
;3.35
G1 X78.989 Y91.929
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1.05575
G1 F900
G1 X78.989 Y90.836 E.21545
G1 X83.172 Y91.929 E.85242
G1 X79.139 Y91.929 E.79517
M73 P66 R0
G1 X78.068 Y92.85 F7800
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X78.068 Y89.636 E.59643
G1 X80.477 Y90.283 E.46281
G1 X90.426 Y92.85 E1.90664
G1 X78.218 Y92.85 E2.2653
M73 P67 R0
G1 X78.317 Y91.881 F7800
;LAYER_CHANGE
;Z:3.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;3.85


M73 P68 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
M73 P69 R0
G1 X78.194 Y92.33 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z3.85 F7800
;AFTER_LAYER_CHANGE
;3.85
G1 X78.917 Y92.001
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:0.911777
G1 F900
G1 X78.917 Y91.075 E.15497
G1 X82.488 Y92.001 E.61706
G1 X79.067 Y92.001 E.5722
G1 X78.068 Y92.85 F7800
;TYPE:External perimeter
;WIDTH:1
M73 P70 R0
G1 F900
G1 X78.068 Y89.968 E.53483
G1 X79.619 Y90.385 E.29797
G1 X89.175 Y92.85 E1.83135
G1 X78.218 Y92.85 E2.03321
M73 P71 R0
G1 X78.254 Y91.867 F7800
;LAYER_CHANGE
;Z:4.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;4.35


M73 P72 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X78.191 Y92.331 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z4.35 F7800
;AFTER_LAYER_CHANGE
;4.35
G1 X78.068 Y92.85
G1 E1 F2400
G1 F900
G1 X78.068 Y90.3 E.47324
G1 X87.924 Y92.85 E1.88919
M73 P73 R0
G1 X78.218 Y92.85 E1.80112
G1 X78.934 Y93.35 F7800
M73 P74 R0
G1 X79.344 Y91.74
;TYPE:Perimeter
;WIDTH:1.43455
G1 F900
G1 X79.261 Y91.884 E.04577
G1 X79.095 Y91.884 E.04577
G1 X79.012 Y91.74 E.04577
G1 X79.095 Y91.596 E.04577
G1 X79.261 Y91.596 E.04577
;LAYER_CHANGE
;Z:4.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;4.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
M73 P75 R0
G1 X79.095 Y91.596 E-.09093
G1 X79.012 Y91.74 E-.09093
G1 X79.095 Y91.884 E-.09093
G1 X79.118 Y91.884 E-.01221
;WIPE_END
G1 E-.015 F3600
G1 Z4.85 F7800
;AFTER_LAYER_CHANGE
;4.85
G1 X78.068 Y92.85
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X78.068 Y90.626 E.41273
G1 X86.678 Y92.85 E1.65013
G1 X78.218 Y92.85 E1.56985
M73 P76 R0
G1 X78.934 Y93.35 F7800
M73 P77 R0
G1 X79.105 Y91.766
;TYPE:Perimeter
;WIDTH:1.15606
G1 F900
G1 X78.973 Y91.766 E.02858
G1 X78.908 Y91.879 E.02858
G1 X78.973 Y91.993 E.02858
G1 X79.105 Y91.993 E.02858
G1 X79.17 Y91.879 E.02858
;LAYER_CHANGE
;Z:5.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;5.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X79.105 Y91.993 E-.07185
G1 X78.973 Y91.993 E-.07185
G1 X78.908 Y91.879 E-.07185
G1 X78.971 Y91.769 E-.06945
;WIPE_END
G1 E-.015 F3600
G1 Z5.35 F7800
;AFTER_LAYER_CHANGE
;5.35
G1 X78.068 Y92.85
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X78.068 Y90.953 E.35209
G1 X85.423 Y92.85 E1.40946
G1 X78.218 Y92.85 E1.33694
M73 P78 R0
G1 X78.934 Y93.35 F7800
M73 P79 R0
G1 X78.992 Y92.022
;TYPE:Perimeter
;WIDTH:0.871131
G1 F900
G1 X78.944 Y92.104 E.01516
G1 X78.849 Y92.104 E.01516
G1 X78.801 Y92.022 E.01516
G1 X78.849 Y91.939 E.01516
G1 X78.944 Y91.939 E.01516
;LAYER_CHANGE
;Z:5.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;5.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X78.849 Y91.939 E-.05233
G1 X78.801 Y92.022 E-.05233
G1 X78.849 Y92.104 E-.05233
G1 X78.944 Y92.104 E-.05233
G1 X78.992 Y92.022 E-.05233
;WIPE_END
G1 E-.03835 F3600
G1 Z5.85 F7800
;AFTER_LAYER_CHANGE
;5.85
G1 X78.189 Y92.729
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:1.24106
G1 F900
G1 X78.189 Y91.431 E.30605
G1 X83.222 Y92.729 E1.22515
G1 X78.339 Y92.729 E1.15096
M73 P80 R0
G1 X79.055 Y93.229 F7800
;LAYER_CHANGE
;Z:6.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;6.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X78.279 Y92.213 E-.285
;WIPE_END
G1 E-.015 F3600
M73 P81 R0
G1 Z6.35 F7800
;AFTER_LAYER_CHANGE
;6.35
G1 X82.527 Y92.8
G1 E1 F2400
;WIDTH:1.10021
G1 F900
G1 X78.118 Y92.8 E.90985
G1 X78.118 Y91.662 E.23473
G1 X82.381 Y92.762 E.90868
G1 X83.027 Y91.934 F7800
;LAYER_CHANGE
;Z:6.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;6.85


M73 P82 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X81.861 Y92.767 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z6.85 F7800
;AFTER_LAYER_CHANGE
;6.85
G1 X78.048 Y92.87
G1 E1 F2400
;WIDTH:0.959351
G1 F900
M73 P83 R0
G1 X78.048 Y91.894 E.17285
G1 X81.831 Y92.87 E.69196
G1 X78.198 Y92.87 E.64345
G1 X78.893 Y93.358 F7800
;LAYER_CHANGE
;Z:7.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;7.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X78.119 Y92.356 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z7.35 F7800
;AFTER_LAYER_CHANGE
;7.35
G1 X78.511 Y92.585
M73 P84 R0
G1 E1 F2400
;WIDTH:1.52969
G1 F900
G1 X78.422 Y92.739 E.05257
G1 X78.244 Y92.739 E.05257
G1 X78.155 Y92.585 E.05257
G1 X78.244 Y92.431 E.05257
G1 X78.422 Y92.431 E.05257
;LAYER_CHANGE
;Z:7.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;7.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X78.244 Y92.431 E-.09745
G1 X78.155 Y92.585 E-.09745
G1 X78.238 Y92.727 E-.09011
;WIPE_END
G1 E-.015 F3600
G1 Z7.85 F7800
;AFTER_LAYER_CHANGE
;7.85
G1 X78.335 Y92.726
G1 E1 F2400
;WIDTH:1.24798
G1 F900
G1 X78.264 Y92.849 E.03381
G1 X78.121 Y92.849 E.03381
G1 X78.05 Y92.726 E.03381
G1 X78.121 Y92.602 E.03381
G1 X78.264 Y92.602 E.03381
;LAYER_CHANGE
;Z:8.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;8.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X78.121 Y92.602 E-.07815
G1 X78.05 Y92.726 E-.07815
G1 X78.121 Y92.849 E-.07815
G1 X78.213 Y92.849 E-.05056
;WIPE_END
G1 E-.015 F3600
G1 Z8.35 F7800
;AFTER_LAYER_CHANGE
;8.35
G1 X78.159 Y92.867
M73 P85 R0
G1 E1 F2400
;WIDTH:0.966277
G1 F900
G1 X78.105 Y92.96 E.01917
G1 X77.998 Y92.96 E.01917
G1 X77.944 Y92.867 E.01917
G1 X77.998 Y92.774 E.01917
G1 X78.105 Y92.774 E.01917
;LAYER_CHANGE
;Z:8.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;8.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X77.998 Y92.774 E-.05885
G1 X77.944 Y92.867 E-.05885
G1 X77.998 Y92.96 E-.05885
G1 X78.105 Y92.96 E-.05885
G1 X78.15 Y92.881 E-.04961
;WIPE_END
G1 E-.015 F3600
G1 Z8.85 F7800
;AFTER_LAYER_CHANGE
;8.85
G1 X78.017 Y93.008
G1 E1 F2400
;WIDTH:0.957301
G1 F900
G1 X77.964 Y93.1 E.01877
G1 X77.857 Y93.1 E.01877
G1 X77.804 Y93.008 E.01877
G1 X77.857 Y92.916 E.01877
G1 X77.964 Y92.916 E.01877
;LAYER_CHANGE
;Z:9.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;9.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X77.857 Y92.916 E-.05823
G1 X77.804 Y93.008 E-.05823
G1 X77.857 Y93.1 E-.05823
G1 X77.964 Y93.1 E-.05823
G1 X78.011 Y93.017 E-.05207
;WIPE_END
G1 E-.015 F3600
G1 Z9.35 F7800
;AFTER_LAYER_CHANGE
;9.35
G1 X77.876 Y93.148
G1 E1 F2400
G1 F900
G1 X77.823 Y93.24 E.01877
G1 X77.717 Y93.24 E.01877
G1 X77.663 Y93.148 E.01877
G1 X77.717 Y93.056 E.01877
M73 P86 R0
G1 X77.823 Y93.056 E.01877
G1 E-.7 F3600
;WIPE_START
G1 F6240;_WIPE
G1 X77.717 Y93.056 E-.05823
G1 F6240;_WIPE
G1 X77.663 Y93.148 E-.05823
G1 F6240;_WIPE
G1 X77.717 Y93.24 E-.05823
G1 F6240;_WIPE
G1 X77.823 Y93.24 E-.05823
G1 F6240;_WIPE
G1 X77.87 Y93.158 E-.05207
;WIPE_END
G1 E-.015 F3600
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G1 Z11.35 F600 ; Move print head up
G1 X5 Y144 F7800 ; present print
G1 Z79.35 F600 ; Move print head further up
M73 P87 R0
G1 Z108 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84 X Y E ; disable motors
M73 P100 R0
; filament used [mm] = 97.07
; filament used [cm3] = 0.23
; filament used [g] = 0.29
; filament cost = 0.00
; total filament used [g] = 0.29
; total filament cost = 0.00
; estimated printing time (normal mode) = 1m 19s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0\n;{layer_z}\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = ;printer_notes=~/.*PRINTER_VENDOR_KINGROON.*/
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "PLA @KP3S"
; default_print_profile = 0.16mm @KP3S
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.8} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84 X Y E ; disable motors
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 1
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #DDDDDD
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 10
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "PLA @KP3S - Copy"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 5%
; fill_pattern = 3dhoneycomb
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 120%
; first_layer_height = 0.35
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = ;"PLA @KP3S";KP3S
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;{layer_z}
; layer_height = 0.5
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 500
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 500
; machine_max_acceleration_y = 500
; machine_max_acceleration_z = 100
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 10
; machine_max_jerk_e = 5
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.75
; max_print_height = 180
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.1
; min_print_speed = 15
; min_skirt_length = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 1
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = 
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 2
; physical_printer_settings_id = KP3S01
; post_process = 
; print_settings_id = KP3S Custom
; printer_model = KP3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_KINGROON\nPRINTER_MODEL_KP3S\n
; printer_settings_id = KP3S - 1.0mm
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 1
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 60
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM140 S{first_layer_bed_temperature[0]} ; set final bed temp\nM104 S150 ; set temporary nozzle temp to prevent oozing during homing and auto bed leveling\nG4 S10 ; allow partial nozzle warmup\nG28 ; home all axisG1 Z50 F240\nG1 X7.6 Y10 F3000\nM104 S{first_layer_temperature[0]} ; set final nozzle temp\nM190 S{first_layer_bed_temperature[0]} ; wait for bed temp to stabilize\nM109 S{first_layer_temperature[0]} ; wait for nozzle temp to stabilize\nG1 Z0.28 F240\nG92 E0\nG1 Y140 E10 F1500 ; prime the nozzle\nG1 X4 F5000\nG92 E0\nG1 Y10 E10 F1200 ; prime the nozzle\nG92 E0
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 20
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 205
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 12
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
