; generated by PrusaSlicer 2.5.0+win64 on 2022-12-07 at 00:03:51 UTC

; 

; external perimeters extrusion width = 1.00mm
; perimeters extrusion width = 1.00mm
; infill extrusion width = 1.00mm
; solid infill extrusion width = 1.00mm
; top infill extrusion width = 1.00mm
; support material extrusion width = 1.00mm
; first layer extrusion width = 0.42mm

M73 P0 R2
M107
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M140 S60 ; set final bed temp
M104 S150 ; set temporary nozzle temp to prevent oozing during homing and auto bed leveling
G4 S10 ; allow partial nozzle warmup
G28 ; home all axisG1 Z50 F240
G1 X7.6 Y10 F3000
M104 S210 ; set final nozzle temp
M190 S60 ; wait for bed temp to stabilize
M109 S210 ; wait for nozzle temp to stabilize
G1 Z0.28 F240
G92 E0
G1 Y140 E10 F1500 ; prime the nozzle
G1 X4 F5000
G92 E0
M73 P4 R1
G1 Y10 E10 F1200 ; prime the nozzle
G92 E0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.35
;HEIGHT:0.35
;BEFORE_LAYER_CHANGE
G92 E0
;0.35


G1 E-1 F3600
M73 P10 R1
G1 Z.35 F7800
;AFTER_LAYER_CHANGE
;0.35
G1 X105.781 Y93.38
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:0.42
M73 P11 R1
G1 F1156
G1 X79.137 Y93.38 E1.33714
G1 X86.506 Y91.615 E.38026
M73 P12 R1
G1 X101.286 Y87.937 E.76437
G1 X105.781 Y87.068 E.22977
M73 P13 R1
G1 X105.781 Y93.23 E.30924
G1 X106.126 Y93.725 F7800
;TYPE:External perimeter
G1 F1156
M73 P14 R1
G1 X76.217 Y93.725 E1.50102
G1 X86.426 Y91.28 E.52683
M73 P15 R1
G1 X101.211 Y87.6 E.76467
G1 X106.126 Y86.65 E.2512
M73 P16 R1
G1 X106.126 Y93.575 E.34752
G1 X105.17 Y93.431 F7800
G1 E-.7 F3600
;WIPE_START
M73 P17 R1
G1 F6240
G1 X105.606 Y93.578 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X105.678 Y87.894 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:0.423087
G1 F1156
G1 X105.223 Y87.439 E.03253
G1 X104.811 Y87.519 E.02127
G1 X105.522 Y88.231 E.05094
G1 X105.522 Y88.723 E.02492
G1 X104.399 Y87.599 E.08048
G1 X103.986 Y87.679 E.02127
G1 X105.522 Y89.215 E.11001
G1 X105.522 Y89.707 E.02492
G1 X103.574 Y87.758 E.13954
G1 X103.161 Y87.838 E.02127
G1 X105.522 Y90.199 E.16907
G1 X105.522 Y90.691 E.02492
G1 X102.749 Y87.918 E.1986
M73 P18 R1
G1 X102.337 Y87.997 E.02127
G1 X105.522 Y91.183 E.22813
G1 X105.522 Y91.675 E.02492
G1 X101.924 Y88.077 E.25766
G1 X101.512 Y88.157 E.02127
G1 X105.522 Y92.168 E.2872
G1 X105.522 Y92.66 E.02492
G1 X101.11 Y88.247 E.31595
G1 X100.716 Y88.345 E.02056
M73 P19 R1
G1 X105.492 Y93.121 E.342
G1 X105 Y93.121 E.02492
G1 X100.322 Y88.444 E.33498
G1 X99.928 Y88.542 E.02056
G1 X104.508 Y93.121 E.32796
G1 X104.016 Y93.121 E.02492
M73 P20 R1
G1 X99.534 Y88.64 E.32094
G1 X99.14 Y88.738 E.02056
G1 X103.524 Y93.121 E.31392
G1 X103.032 Y93.121 E.02492
G1 X98.746 Y88.836 E.30689
G1 X98.352 Y88.934 E.02056
M73 P21 R1
G1 X102.539 Y93.121 E.29987
G1 X102.047 Y93.121 E.02492
G1 X97.958 Y89.032 E.29285
G1 X97.564 Y89.13 E.02056
G1 X101.555 Y93.121 E.28583
G1 X101.063 Y93.121 E.02492
G1 X97.17 Y89.228 E.27881
G1 X96.776 Y89.326 E.02056
M73 P22 R1
G1 X100.571 Y93.121 E.27178
G1 X100.079 Y93.121 E.02492
G1 X96.382 Y89.424 E.26476
G1 X95.987 Y89.522 E.02056
G1 X99.587 Y93.121 E.25774
G1 X99.095 Y93.121 E.02492
M73 P23 R1
G1 X95.593 Y89.62 E.25072
G1 X95.199 Y89.718 E.02056
G1 X98.603 Y93.121 E.2437
G1 X98.11 Y93.121 E.02492
G1 X94.805 Y89.816 E.23667
G1 X94.411 Y89.914 E.02056
G1 X97.618 Y93.121 E.22965
G1 X97.126 Y93.121 E.02492
G1 X94.017 Y90.012 E.22263
M73 P24 R1
G1 X93.623 Y90.111 E.02056
G1 X96.634 Y93.121 E.21561
G1 X96.142 Y93.121 E.02492
G1 X93.229 Y90.209 E.20859
G1 X92.835 Y90.307 E.02056
G1 X95.65 Y93.121 E.20156
G1 X95.158 Y93.121 E.02492
G1 X92.441 Y90.405 E.19454
G1 X92.047 Y90.503 E.02056
M73 P25 R1
G1 X94.666 Y93.121 E.18752
G1 X94.173 Y93.121 E.02492
G1 X91.653 Y90.601 E.1805
G1 X91.259 Y90.699 E.02056
G1 X93.681 Y93.121 E.17348
G1 X93.189 Y93.121 E.02492
G1 X90.865 Y90.797 E.16645
G1 X90.471 Y90.895 E.02056
G1 X92.697 Y93.121 E.15943
G1 X92.205 Y93.121 E.02492
G1 X90.077 Y90.993 E.15241
G1 X89.683 Y91.091 E.02056
M73 P26 R1
G1 X91.713 Y93.121 E.14539
G1 X91.221 Y93.121 E.02492
G1 X89.289 Y91.189 E.13837
G1 X88.895 Y91.287 E.02056
G1 X90.729 Y93.121 E.13134
G1 X90.237 Y93.121 E.02492
G1 X88.5 Y91.385 E.12432
G1 X88.106 Y91.483 E.02056
G1 X89.744 Y93.121 E.1173
G1 X89.252 Y93.121 E.02492
G1 X87.712 Y91.581 E.11028
G1 X87.318 Y91.68 E.02056
G1 X88.76 Y93.121 E.10326
M73 P27 R1
G1 X88.268 Y93.121 E.02492
G1 X86.924 Y91.778 E.09623
G1 X86.53 Y91.875 E.02057
G1 X87.776 Y93.121 E.08923
G1 X87.284 Y93.121 E.02492
G1 X86.133 Y91.97 E.08243
G1 X85.736 Y92.066 E.02067
G1 X86.792 Y93.121 E.07562
G1 X86.3 Y93.121 E.02492
G1 X85.339 Y92.161 E.06881
G1 X84.942 Y92.256 E.02067
G1 X85.808 Y93.121 E.062
G1 X85.315 Y93.121 E.02492
G1 X84.545 Y92.351 E.05519
G1 X84.148 Y92.446 E.02067
G1 X84.823 Y93.121 E.04838
G1 X84.331 Y93.121 E.02492
G1 X83.751 Y92.541 E.04157
G1 X83.354 Y92.636 E.02067
G1 X83.839 Y93.121 E.03476
G1 X83.347 Y93.121 E.02492
M73 P28 R1
G1 X82.957 Y92.731 E.02795
G1 X82.56 Y92.826 E.02067
G1 X82.855 Y93.121 E.02114
G1 X82.363 Y93.121 E.02492
G1 X82.163 Y92.921 E.01433
G1 X81.766 Y93.016 E.02067
G1 X82.026 Y93.277 E.01863
M106 S255
;LAYER_CHANGE
;Z:0.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;0.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X81.766 Y93.016 E-.20166
G1 X81.914 Y92.981 E-.08334
;WIPE_END
G1 E-.015 F3600
G1 Z.85 F7800
;AFTER_LAYER_CHANGE
;0.85
M104 S205 ; set temperature
G1 X104.943 Y92.542
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1
G1 F900
G1 X87.391 Y92.542 E3.25709
G1 X101.482 Y89.037 E2.69455
M73 P29 R1
G1 X104.943 Y88.368 E.65414
M73 P30 R1
G1 X104.943 Y92.392 E.74685
G1 X105.836 Y93.435 F7800
;TYPE:External perimeter
G1 F900
M73 P31 R1
G1 X79.832 Y93.435 E4.82553
G1 X87.274 Y91.652 E1.4201
M73 P32 R1
G1 X101.29 Y88.165 E2.68016
G1 X105.836 Y87.286 E.85927
M73 P33 R1
G1 X105.836 Y93.285 E1.11325
G1 X104.877 Y93.153 F7800
M73 P34 R1
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.316 Y93.288 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X104.675 Y90.429 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:1.01951
G1 F900
G1 X103.231 Y91.873 E.38729
G1 X101.941 Y91.873 E.24463
G1 X104.274 Y89.54 E.62551
G1 X104.274 Y89.179 E.0685
G1 X103.122 Y89.402 E.22237
G1 X100.651 Y91.873 E.66271
M73 P35 R1
G1 X99.361 Y91.873 E.24463
G1 X101.516 Y89.718 E.57776
G1 X99.798 Y90.146 E.3356
G1 X98.071 Y91.873 E.46315
G1 X96.781 Y91.873 E.24463
G1 X98.081 Y90.573 E.34854
G1 X96.363 Y91.001 E.3356
G1 X95.491 Y91.873 E.23392
M73 P36 R1
G1 X94.201 Y91.873 E.24463
G1 X95.197 Y90.877 E.2671
;LAYER_CHANGE
;Z:1.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;1.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X94.829 Y91.244 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z1.35 F7800
;AFTER_LAYER_CHANGE
;1.35
G1 X104.943 Y92.542
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1
G1 F900
G1 X88.743 Y92.542 E3.00633
G1 X101.501 Y89.367 E2.43969
M73 P37 R1
G1 X104.943 Y88.702 E.65066
M73 P38 R1
G1 X104.943 Y92.392 E.6848
G1 X105.836 Y93.435 F7800
;TYPE:External perimeter
G1 F900
G1 X81.197 Y93.435 E4.57233
G1 X88.193 Y91.759 E1.33509
M73 P40 R1
G1 X101.308 Y88.496 E2.50795
G1 X105.836 Y87.62 E.8558
M73 P41 R1
G1 X105.836 Y93.285 E1.05121
G1 X104.874 Y93.162 F7800
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.316 Y93.288 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X103.166 Y89.318 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:1.00283
M73 P42 R1
G1 F900
G1 X104.274 Y90.426 E.2916
G1 X104.274 Y91.692 E.23577
G1 X102.448 Y89.866 E.48075
G1 X101.398 Y90.083 E.19955
G1 X103.188 Y91.873 E.4712
G1 X101.921 Y91.873 E.23577
G1 X100.384 Y90.335 E.40476
G1 X99.37 Y90.588 E.19454
G1 X100.655 Y91.873 E.33832
G1 X99.388 Y91.873 E.23577
M73 P43 R1
G1 X98.355 Y90.84 E.27188
G1 X97.341 Y91.092 E.19454
G1 X98.122 Y91.873 E.20544
G1 X96.855 Y91.873 E.23577
G1 X96.327 Y91.345 E.139
G1 X95.313 Y91.597 E.19454
G1 X95.99 Y92.275 E.17832
;LAYER_CHANGE
;Z:1.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;1.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X95.623 Y91.907 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z1.85 F7800
;AFTER_LAYER_CHANGE
;1.85
G1 X104.943 Y92.542
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1
G1 F900
G1 X90.09 Y92.542 E2.75623
G1 X101.519 Y89.698 E2.18548
M73 P44 R1
G1 X104.943 Y89.036 E.64719
M73 P45 R1
G1 X104.943 Y92.392 E.62275
G1 X105.836 Y93.435 F7800
;TYPE:External perimeter
G1 F900
G1 X82.561 Y93.435 E4.31914
G1 X89.112 Y91.866 E1.25008
M73 P47 R1
G1 X101.326 Y88.826 E2.33575
G1 X105.836 Y87.955 E.85232
M73 P48 R1
G1 X105.836 Y93.285 E.98916
G1 X104.871 Y93.173 F7800
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.316 Y93.288 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X104.675 Y90.45 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:1.00931
M73 P49 R1
G1 F900
G1 X103.253 Y91.873 E.37722
G1 X101.977 Y91.873 E.23919
G1 X103.937 Y89.913 E.51974
G1 X102.356 Y90.218 E.30199
G1 X100.702 Y91.873 E.43869
G1 X99.426 Y91.873 E.23919
G1 X100.709 Y90.59 E.3402
G1 X99.011 Y91.012 E.32814
G1 X98.15 Y91.873 E.22814
G1 X96.875 Y91.873 E.23919
M73 P50 R1
G1 X97.863 Y90.884 E.26221
;LAYER_CHANGE
;Z:2.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;2.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X97.496 Y91.252 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z2.35 F7800
;AFTER_LAYER_CHANGE
;2.35
G1 X104.943 Y92.542
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1
G1 F900
G1 X91.438 Y92.542 E2.50613
G1 X101.537 Y90.029 E1.93127
M73 P51 R0
G1 X104.943 Y89.371 E.64372
G1 X104.943 Y92.392 E.56071
M73 P52 R0
G1 X105.836 Y93.435 F7800
;TYPE:External perimeter
G1 F900
G1 X83.925 Y93.435 E4.06595
G1 X90.031 Y91.973 E1.16507
M73 P53 R0
G1 X101.345 Y89.157 E2.16354
G1 X105.836 Y88.289 E.84885
M73 P54 R0
G1 X105.836 Y93.285 E.92711
G1 X104.868 Y93.184 F7800
M73 P55 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.316 Y93.289 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X104.675 Y91.578 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:1.04131
G1 F900
G1 X103.441 Y90.343 E.33906
G1 X102.334 Y90.557 E.21889
G1 X103.649 Y91.873 E.36126
G1 X102.328 Y91.873 E.25646
G1 X101.247 Y90.791 E.29695
G1 X100.189 Y91.055 E.21162
G1 X101.008 Y91.873 E.22468
G1 X99.687 Y91.873 E.25646
G1 X99.132 Y91.318 E.15241
G1 X98.074 Y91.581 E.21162
M73 P56 R0
G1 X98.767 Y92.275 E.19044
;LAYER_CHANGE
;Z:2.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;2.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X98.4 Y91.907 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z2.85 F7800
;AFTER_LAYER_CHANGE
;2.85
G1 X104.943 Y92.542
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1
G1 F900
G1 X92.786 Y92.542 E2.25604
G1 X101.556 Y90.36 E1.67707
M73 P57 R0
G1 X104.943 Y89.705 E.64024
G1 X104.943 Y92.392 E.49866
G1 X105.836 Y93.435 F7800
;TYPE:External perimeter
M73 P58 R0
G1 F900
G1 X85.29 Y93.435 E3.81276
G1 X90.95 Y92.079 E1.08006
M73 P59 R0
G1 X101.363 Y89.488 E1.99133
G1 X105.836 Y88.623 E.84538
M73 P60 R0
G1 X105.836 Y93.285 E.86506
G1 X104.865 Y93.196 F7800
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.316 Y93.289 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X102.512 Y92.275 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:1.16933
G1 F900
G1 X104.269 Y90.517 E.54859
G1 X102.407 Y90.877 E.41864
M73 P61 R0
G1 X101.411 Y91.873 E.31081
G1 X99.91 Y91.873 E.33158
G1 X101.011 Y90.772 E.34384
;LAYER_CHANGE
;Z:3.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;3.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X100.643 Y91.139 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z3.35 F7800
;AFTER_LAYER_CHANGE
;3.35
G1 X104.943 Y92.542
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1
G1 F900
G1 X94.134 Y92.542 E2.00595
G1 X101.574 Y90.691 E1.42286
M73 P62 R0
G1 X104.943 Y90.039 E.63677
G1 X104.943 Y92.392 E.43661
M73 P63 R0
G1 X105.836 Y93.435 F7800
;TYPE:External perimeter
G1 F900
G1 X86.654 Y93.435 E3.55956
G1 X91.869 Y92.186 E.99505
M73 P64 R0
G1 X101.382 Y89.819 E1.81912
G1 X105.836 Y88.958 E.8419
M73 P65 R0
G1 X105.836 Y93.285 E.80302
G1 X104.862 Y93.21 F7800
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.316 Y93.289 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X102.947 Y90.698 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:1.12595
G1 F900
G1 X104.122 Y91.873 E.35178
G1 X102.681 Y91.873 E.30505
M73 P66 R0
G1 X102.083 Y91.274 E.17922
G1 X101.719 Y91.345 E.07855
G1 X100.913 Y91.545 E.17577
G1 X101.642 Y92.275 E.21841
;LAYER_CHANGE
;Z:3.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;3.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X101.275 Y91.907 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z3.85 F7800
;AFTER_LAYER_CHANGE
;3.85
G1 X104.943 Y92.542
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1
G1 F900
G1 X95.481 Y92.542 E1.75585
G1 X101.593 Y91.022 E1.16865
M73 P67 R0
G1 X104.943 Y90.374 E.6333
G1 X104.943 Y92.392 E.37457
G1 X105.836 Y93.435 F7800
;TYPE:External perimeter
G1 F900
G1 X88.019 Y93.435 E3.30637
G1 X92.788 Y92.293 E.91004
M73 P68 R0
G1 X101.4 Y90.15 E1.64691
M73 P69 R0
G1 X105.836 Y89.292 E.83843
G1 X105.836 Y93.285 E.74097
G1 X104.858 Y93.224 F7800
M73 P70 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.316 Y93.289 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X103.923 Y90.844 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:1.17854
G1 F900
G1 X102.894 Y91.873 E.32403
G1 X101.379 Y91.873 E.33736
G1 X102.045 Y91.207 E.20971
;LAYER_CHANGE
;Z:4.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;4.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X101.677 Y91.575 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z4.35 F7800
;AFTER_LAYER_CHANGE
;4.35
G1 X104.752 Y92.351
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1.38288
G1 F900
G1 X98.391 Y92.351 E1.68661
G1 X101.652 Y91.539 E.8911
M73 P71 R0
G1 X104.752 Y90.94 E.8371
G1 X104.752 Y92.201 E.33428
G1 X105.836 Y93.435 F7800
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X89.383 Y93.435 E3.05318
G1 X93.707 Y92.399 E.82503
M73 P72 R0
G1 X101.418 Y90.48 E1.4747
M73 P73 R0
G1 X105.836 Y89.626 E.83496
G1 X105.836 Y93.285 E.67892
G1 X104.855 Y93.24 F7800
;LAYER_CHANGE
;Z:4.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;4.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
M73 P74 R0
G1 X105.316 Y93.29 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z4.85 F7800
;AFTER_LAYER_CHANGE
;4.85
G1 X104.827 Y92.426
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1.23171
G1 F900
G1 X99.122 Y92.426 E1.33354
G1 X101.654 Y91.796 E.60993
G1 X104.827 Y91.183 E.75539
G1 X104.827 Y92.276 E.25559
G1 X105.836 Y93.435 F7800
;TYPE:External perimeter
;WIDTH:1
G1 F900
M73 P75 R0
G1 X90.747 Y93.435 E2.79999
G1 X94.626 Y92.506 E.74002
G1 X101.437 Y90.811 E1.3025
M73 P76 R0
G1 X105.836 Y89.961 E.83148
G1 X105.836 Y93.285 E.61688
G1 X104.852 Y93.257 F7800
;LAYER_CHANGE
;Z:5.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;5.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
M73 P77 R0
G1 X105.316 Y93.29 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z5.35 F7800
;AFTER_LAYER_CHANGE
;5.35
G1 X104.903 Y92.502
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1.08054
G1 F900
G1 X99.853 Y92.502 E1.02166
G1 X101.656 Y92.053 E.37596
G1 X104.903 Y91.426 E.66898
G1 X104.903 Y92.352 E.1874
G1 X105.836 Y93.435 F7800
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X92.112 Y93.435 E2.54679
G1 X95.544 Y92.613 E.65501
M73 P78 R0
G1 X101.455 Y91.142 E1.13029
G1 X105.836 Y90.295 E.82801
M73 P79 R0
G1 X105.836 Y93.285 E.55483
G1 X104.849 Y93.275 F7800
;LAYER_CHANGE
;Z:5.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;5.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.316 Y93.291 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z5.85 F7800
;AFTER_LAYER_CHANGE
;5.85
G1 X104.979 Y92.578
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:0.929371
G1 F900
G1 X100.584 Y92.578 E.75097
G1 X101.658 Y92.31 E.18921
M73 P80 R0
G1 X104.979 Y91.668 E.57787
G1 X104.979 Y92.428 E.12973
G1 X105.836 Y93.435 F7800
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X93.476 Y93.435 E2.2936
G1 X96.463 Y92.72 E.57
M73 P81 R0
G1 X101.473 Y91.473 E.95808
G1 X105.836 Y90.63 E.82454
G1 X105.836 Y93.285 E.49278
G1 X104.846 Y93.295 F7800
;LAYER_CHANGE
;Z:6.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;6.35


M73 P82 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.316 Y93.291 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z6.35 F7800
;AFTER_LAYER_CHANGE
;6.35
G1 X105.836 Y93.435
G1 E1 F2400
G1 F900
G1 X94.841 Y93.435 E2.04041
G1 X97.382 Y92.826 E.48499
M73 P83 R0
G1 X101.492 Y91.804 E.78587
G1 X105.836 Y90.964 E.82106
G1 X105.836 Y93.285 E.43074
G1 X104.843 Y93.316 F7800
G1 X104.886 Y92.318
;TYPE:Perimeter
;WIDTH:1.4491
G1 F900
G1 X104.803 Y92.463 E.04678
G1 X104.635 Y92.463 E.04678
G1 X104.551 Y92.318 E.04678
G1 X104.635 Y92.173 E.04678
G1 X104.803 Y92.173 E.04678
;LAYER_CHANGE
;Z:6.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;6.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
M73 P84 R0
G1 X104.635 Y92.173 E-.09193
G1 X104.551 Y92.318 E-.09193
G1 X104.635 Y92.463 E-.09193
G1 X104.652 Y92.463 E-.00922
;WIPE_END
G1 E-.015 F3600
G1 Z6.85 F7800
;AFTER_LAYER_CHANGE
;6.85
G1 X105.836 Y93.435
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X96.205 Y93.435 E1.78721
G1 X101.51 Y92.134 E1.01364
G1 X105.836 Y91.298 E.81759
M73 P85 R0
G1 X105.836 Y93.285 E.36869
G1 X104.841 Y93.338 F7800
G1 X105 Y92.469
;TYPE:Perimeter
;WIDTH:1.14676
G1 F900
G1 X104.935 Y92.581 E.02808
G1 X104.805 Y92.581 E.02808
G1 X104.74 Y92.469 E.02808
G1 X104.805 Y92.356 E.02808
G1 X104.935 Y92.356 E.02808
;LAYER_CHANGE
;Z:7.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;7.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X104.805 Y92.356 E-.07121
G1 X104.74 Y92.469 E-.07121
G1 X104.805 Y92.581 E-.07121
G1 X104.935 Y92.581 E-.07121
G1 X104.935 Y92.581 E-.00015
;WIPE_END
G1 E-.015 F3600
G1 Z7.35 F7800
;AFTER_LAYER_CHANGE
;7.35
G1 X105.652 Y93.251
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:1.36856
G1 F900
G1 X99.13 Y93.251 E1.70991
G1 X101.568 Y92.645 E.65874
M73 P86 R0
G1 X105.652 Y91.856 E1.0904
G1 X105.652 Y93.101 E.32638
G1 X104.653 Y93.202 F7800
;LAYER_CHANGE
;Z:7.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;7.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.132 Y93.113 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z7.85 F7800
;AFTER_LAYER_CHANGE
;7.85
G1 X105.727 Y93.326
G1 E1 F2400
;WIDTH:1.21739
G1 F900
M73 P87 R0
G1 X99.814 Y93.326 E1.36464
G1 X101.568 Y92.903 E.41657
G1 X105.727 Y92.099 E.97748
G1 X105.727 Y93.176 E.24868
G1 X104.728 Y93.292 F7800
;LAYER_CHANGE
;Z:8.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;8.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.207 Y93.189 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z8.35 F7800
;AFTER_LAYER_CHANGE
;8.35
G1 X105.803 Y93.402
G1 E1 F2400
;WIDTH:1.06622
M73 P88 R0
G1 F900
G1 X100.562 Y93.402 E1.04462
G1 X101.57 Y93.16 E.20667
G1 X105.803 Y92.341 E.85929
G1 X105.803 Y93.252 E.18149
G1 X104.803 Y93.383 F7800
;LAYER_CHANGE
;Z:8.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;8.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.283 Y93.267 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z8.85 F7800
;AFTER_LAYER_CHANGE
;8.85
G1 X105.879 Y93.478
G1 E1 F2400
;WIDTH:0.913688
G1 F900
M73 P89 R0
G1 X101.323 Y93.478 E.76369
G1 X105.879 Y92.586 E.77818
G1 X105.879 Y93.328 E.12433
G1 X106.379 Y92.612 F7800
;LAYER_CHANGE
;Z:9.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;9.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.359 Y93.345 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z9.35 F7800
;AFTER_LAYER_CHANGE
;9.35
G1 X105.793 Y93.229
G1 E1 F2400
;WIDTH:1.41265
G1 F900
G1 X105.711 Y93.37 E.04428
G1 X105.548 Y93.37 E.04428
G1 X105.466 Y93.229 E.04428
G1 X105.548 Y93.087 E.04428
G1 X105.711 Y93.087 E.04428
;LAYER_CHANGE
;Z:9.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;9.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
M73 P90 R0
G1 X105.548 Y93.087 E-.08943
G1 X105.466 Y93.229 E-.08943
G1 X105.548 Y93.37 E-.08943
G1 X105.578 Y93.37 E-.01671
;WIPE_END
G1 E-.015 F3600
G1 Z9.85 F7800
;AFTER_LAYER_CHANGE
;9.85
G1 X105.908 Y93.382
G1 E1 F2400
;WIDTH:1.10523
G1 F900
G1 X105.846 Y93.49 E.02588
G1 X105.721 Y93.49 E.02588
G1 X105.659 Y93.382 E.02588
G1 X105.721 Y93.274 E.02588
G1 X105.846 Y93.274 E.02588
;LAYER_CHANGE
;Z:10.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;10.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.721 Y93.274 E-.06837
G1 X105.659 Y93.382 E-.06837
G1 X105.721 Y93.49 E-.06837
G1 X105.846 Y93.49 E-.06837
G1 X105.856 Y93.472 E-.01153
;WIPE_END
G1 E-.015 F3600
G1 Z10.35 F7800
;AFTER_LAYER_CHANGE
;10.35
G1 X106.043 Y93.536
G1 E1 F2400
;WIDTH:0.957301
G1 F900
G1 X105.99 Y93.628 E.01877
G1 X105.884 Y93.628 E.01877
G1 X105.831 Y93.536 E.01877
G1 X105.884 Y93.444 E.01877
G1 X105.99 Y93.444 E.01877
;LAYER_CHANGE
;Z:10.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;10.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X105.884 Y93.444 E-.05823
G1 X105.831 Y93.536 E-.05823
G1 X105.884 Y93.628 E-.05823
G1 X105.99 Y93.628 E-.05823
G1 X106.038 Y93.546 E-.05207
;WIPE_END
G1 E-.015 F3600
G1 Z10.85 F7800
;AFTER_LAYER_CHANGE
;10.85
G1 X106.197 Y93.69
G1 E1 F2400
G1 F900
G1 X106.144 Y93.782 E.01877
G1 X106.038 Y93.782 E.01877
G1 X105.984 Y93.69 E.01877
G1 X106.038 Y93.598 E.01877
G1 X106.144 Y93.598 E.01877
G1 E-.7 F3600
;WIPE_START
G1 F6240;_WIPE
G1 X106.038 Y93.598 E-.05823
G1 F6240;_WIPE
G1 X105.984 Y93.69 E-.05823
G1 F6240;_WIPE
G1 X106.038 Y93.782 E-.05823
G1 F6240;_WIPE
G1 X106.144 Y93.782 E-.05823
G1 F6240;_WIPE
G1 X106.191 Y93.7 E-.05207
;WIPE_END
G1 E-.015 F3600
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G1 Z12.85 F600 ; Move print head up
G1 X5 Y144 F7800 ; present print
M73 P91 R0
G1 Z80.85 F600 ; Move print head further up
M73 P92 R0
G1 Z108 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84 X Y E ; disable motors
M73 P100 R0
; filament used [mm] = 197.05
; filament used [cm3] = 0.47
; filament used [g] = 0.59
; filament cost = 0.01
; total filament used [g] = 0.59
; total filament cost = 0.01
; estimated printing time (normal mode) = 2m 0s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0\n;{layer_z}\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = ;printer_notes=~/.*PRINTER_VENDOR_KINGROON.*/
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "PLA @KP3S"
; default_print_profile = 0.16mm @KP3S
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.8} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84 X Y E ; disable motors
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 1
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #DDDDDD
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 10
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "PLA @KP3S - Copy"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 5%
; fill_pattern = 3dhoneycomb
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 120%
; first_layer_height = 0.35
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = ;"PLA @KP3S";KP3S
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;{layer_z}
; layer_height = 0.5
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 500
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 500
; machine_max_acceleration_y = 500
; machine_max_acceleration_z = 100
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 10
; machine_max_jerk_e = 5
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.75
; max_print_height = 180
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.1
; min_print_speed = 15
; min_skirt_length = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 1
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = 
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 2
; physical_printer_settings_id = KP3S01
; post_process = 
; print_settings_id = KP3S Custom
; printer_model = KP3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_KINGROON\nPRINTER_MODEL_KP3S\n
; printer_settings_id = KP3S - 1.0mm
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 1
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 60
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM140 S{first_layer_bed_temperature[0]} ; set final bed temp\nM104 S150 ; set temporary nozzle temp to prevent oozing during homing and auto bed leveling\nG4 S10 ; allow partial nozzle warmup\nG28 ; home all axisG1 Z50 F240\nG1 X7.6 Y10 F3000\nM104 S{first_layer_temperature[0]} ; set final nozzle temp\nM190 S{first_layer_bed_temperature[0]} ; wait for bed temp to stabilize\nM109 S{first_layer_temperature[0]} ; wait for nozzle temp to stabilize\nG1 Z0.28 F240\nG92 E0\nG1 Y140 E10 F1500 ; prime the nozzle\nG1 X4 F5000\nG92 E0\nG1 Y10 E10 F1200 ; prime the nozzle\nG92 E0
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 20
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 205
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 12
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
