; generated by PrusaSlicer 2.5.0+win64 on 2022-12-07 at 00:07:22 UTC

; 

; external perimeters extrusion width = 1.00mm
; perimeters extrusion width = 1.00mm
; infill extrusion width = 1.00mm
; solid infill extrusion width = 1.00mm
; top infill extrusion width = 1.00mm
; support material extrusion width = 1.00mm
; first layer extrusion width = 0.42mm

M73 P0 R1
M107
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M140 S60 ; set final bed temp
M104 S150 ; set temporary nozzle temp to prevent oozing during homing and auto bed leveling
G4 S10 ; allow partial nozzle warmup
G28 ; home all axisG1 Z50 F240
G1 X7.6 Y10 F3000
M104 S210 ; set final nozzle temp
M190 S60 ; wait for bed temp to stabilize
M109 S210 ; wait for nozzle temp to stabilize
G1 Z0.28 F240
G92 E0
G1 Y140 E10 F1500 ; prime the nozzle
G1 X4 F5000
G92 E0
M73 P6 R1
G1 Y10 E10 F1200 ; prime the nozzle
G92 E0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.35
;HEIGHT:0.35
;BEFORE_LAYER_CHANGE
G92 E0
;0.35


G1 E-1 F3600
M73 P13 R1
G1 Z.35 F7800
;AFTER_LAYER_CHANGE
;0.35
M73 P14 R1
G1 X76.988 Y82.784
G1 E1 F2400
;TYPE:Support material interface
;WIDTH:1
M73 P15 R1
G1 F900
G1 X76.988 Y86.98 E.56473
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X76.988 Y86.46 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X78.773 Y85.071 F7800
G1 E1 F2400
G1 F900
G1 X78.773 Y86.578 E.20288
G1 X77.88 Y86.578 E.12014
M73 P16 R1
G1 X77.88 Y83.186 E.45661
G1 X78.773 Y83.186 E.12014
G1 X78.773 Y83.797 E.08232
G1 X79.044 Y83.401 E.06456
G1 X79.666 Y83.401 E.08373
G1 X79.666 Y83.186 E.02901
G1 X80.558 Y83.186 E.12014
G1 X80.558 Y83.401 E.02901
G1 X81.451 Y83.401 E.12014
G1 X81.451 Y83.186 E.02901
G1 X82.344 Y83.186 E.12014
G1 X82.344 Y83.401 E.02901
G1 X83.236 Y83.401 E.12014
G1 X83.236 Y83.186 E.02901
M73 P17 R1
G1 X84.129 Y83.186 E.12014
G1 X84.129 Y83.401 E.02901
G1 X85.022 Y83.401 E.12014
G1 X85.022 Y83.186 E.02901
G1 X85.915 Y83.186 E.12014
G1 X85.915 Y83.401 E.02901
G1 X86.807 Y83.401 E.12014
G1 X86.807 Y83.186 E.02901
G1 X87.7 Y83.186 E.12014
G1 X87.7 Y83.401 E.02901
G1 X88.593 Y83.401 E.12014
G1 X88.593 Y83.186 E.02901
G1 X89.485 Y83.186 E.12014
G1 X89.485 Y83.401 E.02901
G1 X90.378 Y83.401 E.12014
G1 X90.378 Y83.186 E.02901
G1 X91.271 Y83.186 E.12014
G1 X91.271 Y83.401 E.02901
G1 X92.163 Y83.401 E.12014
G1 X92.163 Y83.186 E.02901
M73 P18 R1
G1 X93.056 Y83.186 E.12014
G1 X93.056 Y83.803 E.08307
G1 X91.295 Y84.588 F7800
;TYPE:Support material
;WIDTH:0.42
G1 F900
G1 X91.514 Y84.763 E.01406
G1 X90.981 Y84.763 E.02674
G1 X90.981 Y84.058 E.03537
G1 X91.481 Y84.058 E.02509
G1 X91.312 Y84.539 E.02558
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X91.481 Y84.058 E-.27935
G1 X91.471 Y84.058 E-.00565
;WIPE_END
G1 E-.015 F3600
G1 X99.953 Y85.888 F7800
G1 E1 F2400
G1 F900
G1 X96.054 Y85.888 E.19568
G1 X96.39 Y85.425 E.02867
M73 P19 R1
G1 X97.587 Y85.425 E.0601
G1 X97.891 Y85.27 E.01713
G1 X98.513 Y84.412 E.05315
G1 X98.117 Y83.638 E.04364
G1 X93.981 Y83.638 E.2076
G1 X93.981 Y82.529 E.05562
G1 X90.981 Y82.529 E.15056
G1 X90.981 Y79.95 E.12947
M73 P20 R1
G1 X99.953 Y79.95 E.45029
G1 X99.953 Y85.836 E.29541
M73 P21 R1
G1 X99.512 Y85.732 F7800
G1 F900
G1 X99.512 Y80.26 E.27464
G1 X99.129 Y80.26 E.01923
M73 P22 R1
G1 X99.129 Y85.577 E.26685
G1 X98.746 Y85.577 E.01923
G1 X98.746 Y80.26 E.26685
G1 X98.362 Y80.26 E.01923
G1 X98.362 Y83.435 E.15933
G1 X98.308 Y83.327 E.00606
M73 P23 R1
G1 X97.979 Y83.327 E.01648
G1 X97.979 Y80.26 E.15394
G1 X97.596 Y80.26 E.01923
G1 X97.596 Y83.327 E.15394
G1 X97.213 Y83.327 E.01923
G1 X97.213 Y80.26 E.15394
G1 X96.83 Y80.26 E.01923
M73 P24 R1
G1 X96.83 Y83.327 E.15394
G1 X96.446 Y83.327 E.01923
G1 X96.446 Y80.26 E.15394
G1 X96.063 Y80.26 E.01923
G1 X96.063 Y83.327 E.15394
G1 X95.68 Y83.327 E.01923
G1 X95.68 Y80.26 E.15394
G1 X95.297 Y80.26 E.01923
M73 P25 R1
G1 X95.297 Y83.327 E.15394
G1 X94.913 Y83.327 E.01923
G1 X94.913 Y80.26 E.15394
G1 X94.53 Y80.26 E.01923
G1 X94.53 Y83.327 E.15394
G1 X94.291 Y83.327 E.01199
G1 X94.291 Y82.219 E.05562
G1 X94.147 Y82.219 E.00724
M73 P26 R1
G1 X94.147 Y80.26 E.09831
G1 X93.764 Y80.26 E.01923
G1 X93.764 Y82.219 E.09831
G1 X93.381 Y82.219 E.01923
G1 X93.381 Y80.26 E.09831
G1 X92.997 Y80.26 E.01923
G1 X92.997 Y82.219 E.09831
G1 X92.614 Y82.219 E.01923
G1 X92.614 Y80.26 E.09831
G1 X92.231 Y80.26 E.01923
M73 P27 R1
G1 X92.231 Y82.219 E.09831
G1 X91.848 Y82.219 E.01923
G1 X91.848 Y80.26 E.09831
G1 X91.465 Y80.26 E.01923
G1 X91.465 Y82.374 E.1061
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X91.465 Y81.854 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X98.362 Y85.732 F7800
G1 E1 F2400
G1 F900
M73 P28 R1
G1 X98.362 Y85.149 E.02929
G1 X98.099 Y85.512 E.02254
G1 X97.979 Y85.573 E.00674
G1 X97.979 Y85.732 E.00798
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X97.979 Y85.573 E-.08711
G1 X98.099 Y85.512 E-.07361
G1 X98.232 Y85.329 E-.12428
;WIPE_END
G1 E-.015 F3600
G1 X96.627 Y93.766 F7800
G1 E1 F2400
;TYPE:Support material interface
;WIDTH:1
G1 F900
G1 X96.627 Y88.724 E.67848
G1 X95.734 Y88.724 E.12014
G1 X95.734 Y93.364 E.62442
M73 P29 R1
G1 X94.842 Y93.364 E.12014
G1 X94.842 Y88.796 E.6148
G1 X94.127 Y89.605 E.14526
G1 X93.949 Y89.727 E.02906
G1 X93.949 Y93.364 E.48953
G1 X93.056 Y93.364 E.12014
M73 P30 R1
G1 X93.056 Y90.091 E.44048
G1 X92.163 Y90.417 E.12792
G1 X92.163 Y93.364 E.39656
G1 X91.271 Y93.364 E.12014
G1 X91.271 Y90.744 E.35264
G1 X90.378 Y91.07 E.12792
M73 P31 R1
G1 X90.378 Y93.364 E.30872
G1 X89.932 Y93.364 E.06006
G1 X89.932 Y96.757 E.4566
G1 X89.485 Y96.757 E.06008
G1 X89.485 Y91.396 E.7214
G1 X88.593 Y91.723 E.12792
M73 P32 R1
G1 X88.593 Y96.757 E.67748
G1 X87.7 Y96.757 E.12014
M73 P32 R0
G1 X87.7 Y92.049 E.63356
G1 X86.807 Y92.375 E.12792
M73 P33 R0
G1 X86.807 Y96.757 E.58964
G1 X85.915 Y96.757 E.12014
G1 X85.915 Y92.702 E.54572
G1 X85.022 Y93.028 E.12792
G1 X85.022 Y96.757 E.5018
G1 X84.129 Y96.757 E.12014
M73 P34 R0
G1 X84.129 Y93.354 E.45788
G1 X83.824 Y93.466 E.04374
G1 X83.236 Y93.402 E.07953
G1 X83.236 Y96.757 E.45145
G1 X82.344 Y96.757 E.12014
G1 X82.344 Y92.878 E.52195
M73 P35 R0
G1 X81.451 Y92.31 E.1424
G1 X81.451 Y96.757 E.5984
G1 X80.558 Y96.757 E.12014
G1 X80.558 Y89.64 E.95773
G1 E-.7 F3600
;WIPE_START
M73 P36 R0
G1 F6240
G1 X80.558 Y90.16 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X97.323 Y84.531 F7800
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:0.925111
G1 F900
G1 X93.827 Y84.531 E.43233
G1 X93.697 Y84.554 E.01638
;WIDTH:0.877699
M73 P37 R0
G1 X93.566 Y84.577 E.01547
;WIDTH:0.830287
G1 X93.436 Y84.6 E.01455
;WIDTH:0.782876
G1 X93.305 Y84.622 E.01364
;WIDTH:0.735464
G1 X93.175 Y84.645 E.01273
;WIDTH:0.688052
G1 X93.044 Y84.668 E.01181
M106 S255
;LAYER_CHANGE
;Z:0.65
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0
;0.65


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X93.175 Y84.645 E-.07259
G1 X93.305 Y84.622 E-.07259
G1 X93.436 Y84.6 E-.07259
G1 X93.557 Y84.579 E-.06722
;WIPE_END
G1 E-.015 F3600
G1 Z.65 F7800
;AFTER_LAYER_CHANGE
;0.65
M104 S205 ; set temperature
G1 X93.056 Y83.803
G1 E1 F2400
;TYPE:Support material interface
;WIDTH:1
G1 F900
G1 X93.056 Y83.186 E.07203
G1 X92.163 Y83.186 E.10417
G1 X92.163 Y83.401 E.02515
G1 X91.271 Y83.401 E.10417
G1 X91.271 Y83.186 E.02515
G1 X90.378 Y83.186 E.10417
G1 X90.378 Y83.401 E.02515
G1 X89.485 Y83.401 E.10417
G1 X89.485 Y83.186 E.02515
M73 P38 R0
G1 X88.593 Y83.186 E.10417
G1 X88.593 Y83.401 E.02515
G1 X87.7 Y83.401 E.10417
G1 X87.7 Y83.186 E.02515
G1 X86.807 Y83.186 E.10417
G1 X86.807 Y83.401 E.02515
G1 X85.915 Y83.401 E.10417
G1 X85.915 Y83.186 E.02515
G1 X85.022 Y83.186 E.10417
G1 X85.022 Y83.401 E.02515
G1 X84.129 Y83.401 E.10417
G1 X84.129 Y83.186 E.02515
G1 X83.236 Y83.186 E.10417
G1 X83.236 Y83.401 E.02515
G1 X82.344 Y83.401 E.10417
G1 X82.344 Y83.186 E.02515
G1 X81.451 Y83.186 E.10417
G1 X81.451 Y83.401 E.02515
G1 X80.558 Y83.401 E.10417
G1 X80.558 Y83.186 E.02515
G1 X79.666 Y83.186 E.10417
M73 P39 R0
G1 X79.666 Y83.401 E.02515
G1 X79.044 Y83.401 E.0726
G1 X78.773 Y83.797 E.05598
G1 X78.773 Y83.186 E.07138
G1 X77.88 Y83.186 E.10417
G1 X77.88 Y86.578 E.39592
G1 X78.773 Y86.578 E.10417
G1 X78.773 Y85.071 E.17591
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X78.773 Y85.591 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X76.988 Y86.98 F7800
G1 E1 F2400
M73 P40 R0
G1 F900
G1 X76.988 Y82.784 E.48967
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X76.988 Y83.304 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X80.558 Y89.64 F7800
G1 E1 F2400
G1 F900
G1 X80.558 Y96.757 E.83043
G1 X81.451 Y96.757 E.10417
M73 P41 R0
G1 X81.451 Y92.31 E.51887
G1 X82.344 Y92.878 E.12348
G1 X82.344 Y96.757 E.45258
G1 X83.236 Y96.757 E.10417
M73 P42 R0
G1 X83.236 Y93.402 E.39144
G1 X83.824 Y93.466 E.06896
G1 X84.129 Y93.354 E.03792
G1 X84.129 Y96.757 E.39702
G1 X85.022 Y96.757 E.10417
G1 X85.022 Y93.028 E.43511
G1 X85.915 Y92.702 E.11092
M73 P43 R0
G1 X85.915 Y96.757 E.47319
G1 X86.807 Y96.757 E.10417
G1 X86.807 Y92.375 E.51127
G1 X87.7 Y92.049 E.11092
M73 P44 R0
G1 X87.7 Y96.757 E.54936
G1 X88.593 Y96.757 E.10417
G1 X88.593 Y91.723 E.58744
G1 X89.485 Y91.396 E.11092
G1 X89.485 Y96.757 E.62552
M73 P45 R0
G1 X89.932 Y96.757 E.05209
G1 X89.932 Y93.364 E.39591
G1 X90.378 Y93.364 E.05208
G1 X90.378 Y91.07 E.26769
G1 X91.271 Y90.744 E.11092
G1 X91.271 Y93.364 E.30577
M73 P46 R0
G1 X92.163 Y93.364 E.10417
G1 X92.163 Y90.417 E.34386
G1 X93.056 Y90.091 E.11092
G1 X93.056 Y93.364 E.38194
G1 X93.949 Y93.364 E.10417
G1 X93.949 Y89.727 E.42446
G1 X94.127 Y89.605 E.0252
M73 P47 R0
G1 X94.842 Y88.796 E.12595
G1 X94.842 Y93.364 E.53308
G1 X95.734 Y93.364 E.10417
G1 X95.734 Y88.724 E.54143
G1 X96.627 Y88.724 E.10417
M73 P48 R0
G1 X96.627 Y93.766 E.58831
;LAYER_CHANGE
;Z:0.75
;HEIGHT:0.1
;BEFORE_LAYER_CHANGE
G92 E0
;0.75


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X96.627 Y93.246 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z.75 F7800
;AFTER_LAYER_CHANGE
;0.75
G1 X96.627 Y93.766
G1 E1 F2400
G1 F900
G1 X96.627 Y88.724 E.2051
G1 X96.091 Y88.724 E.02179
M73 P49 R0
G1 X96.439 Y89.031 E.01887
G1 X96.309 Y89.179 E.00801
G1 X96.389 Y89.322 E.00666
G1 X95.981 Y89.55 E.01902
G1 X95.734 Y89.83 E.01516
G1 X95.734 Y93.364 E.14379
G1 X94.842 Y93.364 E.03632
G1 X94.842 Y90.841 E.10266
G1 X93.949 Y91.852 E.05487
M73 P50 R0
G1 X93.949 Y93.364 E.06153
G1 X93.056 Y93.364 E.03632
G1 X93.056 Y92.296 E.04346
G1 X92.163 Y92.622 E.03867
G1 X92.163 Y93.364 E.03019
G1 X91.271 Y93.364 E.03632
G1 X91.271 Y92.948 E.01691
G1 X90.378 Y93.275 E.03867
G1 X90.378 Y93.766 E.01998
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X90.378 Y93.275 E-.26914
G1 X90.405 Y93.265 E-.01586
;WIPE_END
G1 E-.015 F3600
G1 X89.485 Y97.158 F7800
G1 E1 F2400
M73 P51 R0
G1 F900
G1 X89.485 Y93.601 E.14473
G1 X88.593 Y93.927 E.03867
G1 X88.593 Y96.757 E.11511
G1 X87.7 Y96.757 E.03632
G1 X87.7 Y94.254 E.10183
G1 X86.807 Y94.58 E.03867
G1 X86.807 Y96.757 E.08855
M73 P52 R0
G1 X85.915 Y96.757 E.03632
G1 X85.915 Y94.906 E.07528
G1 X85.022 Y95.233 E.03867
G1 X85.022 Y96.757 E.062
G1 X84.129 Y96.757 E.03632
G1 X84.129 Y95.287 E.05977
G1 X84.031 Y95.277 E.00402
G1 X83.236 Y94.771 E.03831
G1 X83.236 Y96.757 E.08077
G1 X82.344 Y96.757 E.03632
M73 P53 R0
G1 X82.344 Y94.203 E.10388
G1 X81.451 Y93.635 E.04305
G1 X81.451 Y96.757 E.12699
G1 X80.558 Y96.757 E.03632
G1 X80.558 Y92.591 E.16947
G1 E-.7 F3600
;WIPE_START
M73 P54 R0
G1 F6240
G1 X80.558 Y93.111 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X96.664 Y83.348 F7800
G1 E1 F2400
;TYPE:Support material
;HEIGHT:0.4
G1 F900
G1 X94.271 Y83.348 E.36375
;HEIGHT:0.1
G1 X77.693 Y83.348 E.67443
G1 X76.8 Y84.656 E.06445
M73 P56 R0
G1 X77.53 Y86.525 E.08164
G1 X76.415 Y86.525 E.04538
G1 X76.415 Y83.239 E.13366
G1 X94.271 Y83.239 E.72644
;HEIGHT:0.4
G1 X96.635 Y83.239 E.35936
;LAYER_CHANGE
;Z:0.85
;HEIGHT:0.1
;BEFORE_LAYER_CHANGE
G92 E0
;0.85


M73 P58 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X96.115 Y83.239 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z.85 F7800
;AFTER_LAYER_CHANGE
;0.85
G1 X92.357 Y84.952
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:1.20832
;HEIGHT:0.5
G1 F900
G1 X97.862 Y84.952 E1.26007
;TYPE:Overhang perimeter
;WIDTH:1
;HEIGHT:1
G1 X98.071 Y84.952 E.06804
M73 P59 R0
G1 X97.438 Y85.825 E.35225
G1 X97.273 Y86.053 E.09173
G1 X93.733 Y86.053 E1.15597
G1 X93.08 Y85.53 E.27302
;TYPE:External perimeter
;WIDTH:1.20832
;HEIGHT:0.5
G1 X92.474 Y85.046 E.17761
;LAYER_CHANGE
;Z:1.15
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0
;1.15


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X92.994 Y85.036 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z1.15 F7800
;AFTER_LAYER_CHANGE
;1.15
G1 X90.378 Y93.766
G1 E1 F2400
;TYPE:Support material interface
;WIDTH:1
;HEIGHT:0.4
M73 P60 R0
G1 F900
G1 X90.378 Y93.275 E.07465
G1 X91.271 Y92.948 E.1445
G1 X91.271 Y93.364 E.0632
G1 X92.163 Y93.364 E.13571
G1 X92.163 Y92.622 E.11281
G1 X93.056 Y92.296 E.1445
G1 X93.056 Y93.364 E.16242
G1 X93.949 Y93.364 E.13571
G1 X93.949 Y91.852 E.22991
G1 X94.842 Y90.841 E.20504
G1 X94.842 Y93.364 E.38361
G1 X95.734 Y93.364 E.13571
M73 P61 R0
G1 X95.734 Y89.83 E.53732
G1 X95.981 Y89.55 E.05665
G1 X96.389 Y89.322 E.07109
G1 X96.309 Y89.179 E.0249
G1 X96.439 Y89.031 E.02993
G1 X96.091 Y88.724 E.07051
G1 X96.627 Y88.724 E.08141
G1 X96.627 Y93.766 E.76642
G1 E-.7 F3600
;WIPE_START
M73 P62 R0
G1 F6240
G1 X96.627 Y93.246 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X89.485 Y97.158 F7800
G1 E1 F2400
G1 F900
G1 X89.485 Y93.601 E.54082
G1 X88.593 Y93.927 E.1445
G1 X88.593 Y96.757 E.43014
G1 X87.7 Y96.757 E.13571
M73 P63 R0
G1 X87.7 Y94.254 E.38052
G1 X86.807 Y94.58 E.1445
G1 X86.807 Y96.757 E.33091
G1 X85.915 Y96.757 E.13571
G1 X85.915 Y94.906 E.2813
G1 X85.022 Y95.233 E.1445
G1 X85.022 Y96.757 E.23169
G1 X84.129 Y96.757 E.13571
M73 P64 R0
G1 X84.129 Y95.287 E.22337
G1 X84.031 Y95.277 E.01504
G1 X83.236 Y94.771 E.14314
G1 X83.236 Y96.757 E.30183
G1 X82.344 Y96.757 E.13571
G1 X82.344 Y94.203 E.38819
G1 X81.451 Y93.635 E.16086
G1 X81.451 Y96.757 E.47455
G1 X80.558 Y96.757 E.13571
M73 P65 R0
G1 X80.558 Y92.591 E.6333
;LAYER_CHANGE
;Z:1.35
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0
;1.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X80.558 Y93.111 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z1.35 F7800
;AFTER_LAYER_CHANGE
;1.35
G1 X98.081 Y85.678
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:0.87608
;HEIGHT:0.5
M73 P66 R0
G1 F900
G1 X97.639 Y86.288 E.12038
;WIDTH:0.876079
G1 X97.524 Y86.447 E.03135
G1 X94.454 Y86.447 E.49067
;WIDTH:0.908301
G1 X94.173 Y86.494 E.04745
;WIDTH:0.940523
G1 X93.892 Y86.542 E.04935
;WIDTH:0.970261
G1 X93.671 Y86.69 E.04771
;WIDTH:1
G1 X93.45 Y86.838 E.04935
G1 X93.242 Y87.074 E.05842
;TYPE:Overhang perimeter
;WIDTH:1
;HEIGHT:1
G1 X92.643 Y87.751 E.29512
G1 X83.752 Y91.002 E3.09126
G1 X82.978 Y90.509 E.29953
M73 P67 R0
G1 X81.114 Y85.74 E1.6719
G1 X91.575 Y85.74 E3.4157
;TYPE:Perimeter
;WIDTH:1
;HEIGHT:0.5
G1 X93.329 Y85.725 E.32558
;WIDTH:0.970261
M73 P68 R0
G1 X93.704 Y85.711 E.06727
;WIDTH:0.940523
G1 X94.079 Y85.694 E.06496
;WIDTH:0.908301
G1 X94.454 Y85.678 E.06245
;WIDTH:0.87608
G1 X97.931 Y85.678 E.55573
G1 X99.51 Y84.848 F7800
;TYPE:Overhang perimeter
;WIDTH:1
;HEIGHT:1
M73 P69 R0
G1 F1145.916
G1 X99.709 Y84.848 E.06505
G1 X98.312 Y86.776 E.77752
G1 X97.948 Y87.278 E.20248
G1 X94.377 Y87.285 E1.16618
G1 X94.119 Y87.429 E.09636
G1 X93.163 Y88.512 E.47187
G1 X83.644 Y91.992 E3.30914
G1 X82.253 Y91.106 E.53868
M73 P70 R0
G1 X79.807 Y84.848 E2.19399
G1 X90.46 Y84.848 E3.4783
;TYPE:External perimeter
;WIDTH:1
;HEIGHT:0.5
G1 F900
M73 P71 R0
G1 X99.36 Y84.848 E1.65163
G1 E-.7 F3600
;WIPE_START
M73 P72 R0
G1 F6240
G1 X99.709 Y84.848 E-.1914
G1 X99.609 Y84.986 E-.0936
;WIPE_END
G1 E-.015 F3600
G1 X91.702 Y86.016 F7800
G1 E1 F2400
;TYPE:Bridge infill
;WIDTH:1.0221
;HEIGHT:1
G1 F1096.897
G1 X92.486 Y86.799 E.37793
G1 X92.208 Y87.114 E.14313
G1 X91.532 Y87.361 E.24575
G1 X90.659 Y86.489 E.42104
G1 X89.143 Y86.489 E.5172
G1 X90.421 Y87.767 E.61685
G1 X89.311 Y88.173 E.40326
M73 P73 R0
G1 X87.626 Y86.489 E.81266
G1 X86.11 Y86.489 E.5172
G1 X88.201 Y88.579 E1.00847
G1 X87.09 Y88.985 E.40326
G1 X84.594 Y86.489 E1.20428
G1 X83.078 Y86.489 E.5172
G1 X85.98 Y89.391 E1.40009
G1 X84.87 Y89.797 E.40326
M73 P74 R0
G1 X81.793 Y86.72 E1.48418
;LAYER_CHANGE
;Z:1.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;1.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X82.161 Y87.088 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z1.85 F7800
;AFTER_LAYER_CHANGE
;1.85
G1 X94.711 Y87.501
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1.15171
M73 P75 R0
G1 F900
G1 X94.688 Y87.524 E.00706
;WIDTH:1.11378
G1 X94.589 Y87.622 E.02915
;WIDTH:1.07585
G1 X94.489 Y87.72 E.02805
;WIDTH:1.03793
G1 X94.39 Y87.818 E.02695
;WIDTH:1
G1 X92.682 Y89.753 E.479
;TYPE:Overhang perimeter
;WIDTH:1
;HEIGHT:1
G1 F1145.916
G1 X92.435 Y90.032 E.1218
G1 X84.63 Y92.885 E2.71355
G1 X84.441 Y92.765 E.07315
;TYPE:Perimeter
;WIDTH:1
;HEIGHT:0.5
G1 F900
G1 X81.907 Y91.153 E.55731
G1 X79.792 Y85.74 E1.07836
M73 P76 R0
G1 X93.453 Y85.74 E2.53508
;WIDTH:1.03793
G1 X93.696 Y85.759 E.04707
;WIDTH:1.07585
M73 P77 R0
G1 X93.939 Y85.778 E.04899
;WIDTH:1.11378
G1 X94.181 Y85.797 E.05091
;WIDTH:1.15171
G1 X94.424 Y85.816 E.05283
;WIDTH:1.19781
G1 X94.543 Y85.839 E.02752
;WIDTH:1.24391
G1 X94.662 Y85.862 E.02868
;WIDTH:1.29001
G1 X94.781 Y85.885 E.02984
;WIDTH:1.33611
G1 X94.9 Y85.908 E.03101
;WIDTH:1.38222
G1 X95.02 Y85.931 E.03217
G1 X95.394 Y85.923 E.09928
;WIDTH:1.36592
G1 X98.985 Y85.923 E.93948
G1 X98.261 Y86.922 E.32265
M73 P78 R0
G1 X98.073 Y87.182 E.08402
G1 X95.394 Y87.182 E.70086
;WIDTH:1.38222
G1 X95.13 Y87.197 E.07018
G1 X95.061 Y87.243 E.02186
;WIDTH:1.33611
G1 X94.993 Y87.288 E.02107
;WIDTH:1.29001
G1 X94.924 Y87.334 E.02028
;WIDTH:1.24391
G1 X94.855 Y87.38 E.01949
;WIDTH:1.19781
G1 X94.823 Y87.402 E.00891
G1 X95.394 Y88.258 F7800
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X95.293 Y88.278 E.0192
;TYPE:Overhang perimeter
;WIDTH:1
;HEIGHT:1
G1 F1145.916
G1 X95.06 Y88.408 E.08726
G1 X92.954 Y90.793 E1.03861
G1 X84.523 Y93.875 E2.93142
G1 X81.182 Y91.749 E1.29294
M73 P79 R0
G1 X78.485 Y84.848 E2.41957
G1 X78.734 Y84.848 E.08114
;TYPE:External perimeter
;WIDTH:1
;HEIGHT:0.5
M73 P80 R0
G1 F900
G1 X100.944 Y84.848 E4.12159
;TYPE:Overhang perimeter
;WIDTH:1
;HEIGHT:1
G1 F1145.916
M73 P81 R0
G1 X101.093 Y84.848 E.04859
G1 X99.132 Y87.553 E1.09096
G1 X98.686 Y88.169 E.24837
G1 X98.511 Y88.258 E.06415
G1 X98.246 Y88.258 E.08642
;TYPE:External perimeter
;WIDTH:1
;HEIGHT:0.5
M73 P82 R0
G1 F900
G1 X95.544 Y88.258 E.50139
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X95.293 Y88.278 E-.13825
;WIPE_END
G1 E-.16175 F3600
G1 X93.295 Y88.644 F7800
G1 E1 F2400
;TYPE:Bridge infill
;WIDTH:1.03145
;HEIGHT:1
G1 F1077.111
G1 X83.488 Y91.272 E3.52723
G1 X82.515 Y90.653 E.40049
M73 P83 R0
G1 X82.43 Y90.436 E.08104
G1 X93.767 Y87.398 E4.07723
G1 X94.325 Y86.767 E.29262
M73 P84 R0
G1 X94.22 Y86.612 E.06523
G1 X93.43 Y86.489 E.27765
G1 X92.983 Y86.489 E.15541
G1 X87.691 Y87.906 E1.9029
G1 X87.91 Y87.723 F7800
;TYPE:Top solid infill
;WIDTH:1.00771
;HEIGHT:0.5
G1 F900
G1 X89.223 Y86.41 E.34758
G1 X87.95 Y86.41 E.23834
G1 X86.577 Y87.783 E.36335
G1 X84.57 Y88.516 E.39999
G1 X86.676 Y86.41 E.55757
M73 P85 R0
G1 X85.403 Y86.41 E.23834
G1 X82.563 Y89.25 E.75179
G1 X81.968 Y89.468 E.11862
G1 X81.716 Y88.824 E.12943
G1 X84.13 Y86.41 E.6389
G1 X82.856 Y86.41 E.23834
M73 P86 R0
G1 X81.358 Y87.908 E.39654
G1 X81 Y86.992 E.18399
G1 X81.984 Y86.008 E.26051
G1 E-.7 F3600
;WIPE_START
G1 F6240;_WIPE
G1 X81.617 Y86.376 E-.285
;WIPE_END
G1 E-.015 F3600
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G1 Z3.85 F600 ; Move print head up
G1 X5 Y144 F7800 ; present print
G1 Z71.85 F600 ; Move print head further up
M73 P88 R0
G1 Z108 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84 X Y E ; disable motors
M73 P100 R0
; filament used [mm] = 131.15
; filament used [cm3] = 0.32
; filament used [g] = 0.39
; filament cost = 0.00
; total filament used [g] = 0.39
; total filament cost = 0.00
; estimated printing time (normal mode) = 1m 27s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0\n;{layer_z}\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = ;printer_notes=~/.*PRINTER_VENDOR_KINGROON.*/
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "PLA @KP3S"
; default_print_profile = 0.16mm @KP3S
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.8} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84 X Y E ; disable motors
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 1
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #DDDDDD
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 10
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "PLA @KP3S - Copy"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 5%
; fill_pattern = 3dhoneycomb
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 120%
; first_layer_height = 0.35
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = ;"PLA @KP3S";KP3S
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;{layer_z}
; layer_height = 0.5
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 500
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 500
; machine_max_acceleration_y = 500
; machine_max_acceleration_z = 100
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 10
; machine_max_jerk_e = 5
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.75
; max_print_height = 180
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.1
; min_print_speed = 15
; min_skirt_length = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 1
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = 
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 2
; physical_printer_settings_id = KP3S01
; post_process = 
; print_settings_id = KP3S Custom
; printer_model = KP3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_KINGROON\nPRINTER_MODEL_KP3S\n
; printer_settings_id = KP3S - 1.0mm
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 1
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 60
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM140 S{first_layer_bed_temperature[0]} ; set final bed temp\nM104 S150 ; set temporary nozzle temp to prevent oozing during homing and auto bed leveling\nG4 S10 ; allow partial nozzle warmup\nG28 ; home all axisG1 Z50 F240\nG1 X7.6 Y10 F3000\nM104 S{first_layer_temperature[0]} ; set final nozzle temp\nM190 S{first_layer_bed_temperature[0]} ; wait for bed temp to stabilize\nM109 S{first_layer_temperature[0]} ; wait for nozzle temp to stabilize\nG1 Z0.28 F240\nG92 E0\nG1 Y140 E10 F1500 ; prime the nozzle\nG1 X4 F5000\nG92 E0\nG1 Y10 E10 F1200 ; prime the nozzle\nG92 E0
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 20
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 205
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 12
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
