; generated by PrusaSlicer 2.5.0+win64 on 2022-12-07 at 00:19:05 UTC

; 

; external perimeters extrusion width = 1.00mm
; perimeters extrusion width = 1.00mm
; infill extrusion width = 1.00mm
; solid infill extrusion width = 1.00mm
; top infill extrusion width = 1.00mm
; support material extrusion width = 1.00mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M107
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M140 S60 ; set final bed temp
M104 S150 ; set temporary nozzle temp to prevent oozing during homing and auto bed leveling
G4 S10 ; allow partial nozzle warmup
G28 ; home all axisG1 Z50 F240
G1 X7.6 Y10 F3000
M104 S210 ; set final nozzle temp
M190 S60 ; wait for bed temp to stabilize
M109 S210 ; wait for nozzle temp to stabilize
G1 Z0.28 F240
G92 E0
G1 Y140 E10 F1500 ; prime the nozzle
G1 X4 F5000
G92 E0
M73 P12 R0
G1 Y10 E10 F1200 ; prime the nozzle
G92 E0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.35
;HEIGHT:0.35
;BEFORE_LAYER_CHANGE
G92 E0
;0.35


G1 E-1 F3600
M73 P26 R0
G1 Z.35 F7800
;AFTER_LAYER_CHANGE
;0.35
G1 X85.873 Y87.268
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:0.42
M73 P29 R0
G1 F900
G1 X92.579 Y94.428 E.49232
G1 X85.873 Y94.428 E.33653
M73 P30 R0
G1 X85.873 Y87.418 E.35182
M73 P31 R0
G1 X85.529 Y86.395 F7800
;TYPE:External perimeter
M73 P32 R0
G1 F900
G1 X93.375 Y94.773 E.57605
G1 X85.529 Y94.773 E.39376
M73 P34 R0
G1 X85.529 Y86.545 E.41293
M73 P35 R0
G1 X84.555 Y86.622 F7800
M73 P36 R0
G1 X85.977 Y88.238
;TYPE:Solid infill
;WIDTH:0.421384
G1 F900
M73 P37 R0
G1 X91.908 Y94.169 E.42267
G1 X91.419 Y94.169 E.02467
M73 P38 R0
G1 X86.132 Y88.883 E.37672
G1 X86.132 Y89.372 E.02467
M73 P39 R0
G1 X90.929 Y94.169 E.34182
G1 X90.439 Y94.169 E.02467
M73 P40 R0
G1 X86.132 Y89.862 E.30693
G1 X86.132 Y90.352 E.02467
M73 P41 R0
G1 X89.95 Y94.169 E.27203
G1 X89.46 Y94.169 E.02467
M73 P42 R0
G1 X86.132 Y90.841 E.23714
G1 X86.132 Y91.331 E.02467
M73 P43 R0
G1 X88.97 Y94.169 E.20224
G1 X88.481 Y94.169 E.02467
G1 X86.132 Y91.821 E.16734
G1 X86.132 Y92.311 E.02467
M73 P44 R0
G1 X87.991 Y94.169 E.13245
G1 X87.501 Y94.169 E.02467
G1 X86.132 Y92.8 E.09755
G1 X86.132 Y93.29 E.02467
M73 P45 R0
G1 X87.011 Y94.169 E.06266
G1 X86.522 Y94.169 E.02467
G1 X85.977 Y93.624 E.03882
M106 S255
;LAYER_CHANGE
;Z:0.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;0.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X86.345 Y93.992 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z.85 F7800
;AFTER_LAYER_CHANGE
;0.85
M104 S205 ; set temperature
G1 X86.711 Y90.132
M73 P46 R0
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1
G1 F900
G1 X89.95 Y93.59 E.87928
G1 X86.711 Y93.59 E.60103
M73 P47 R0
G1 X86.711 Y90.282 E.61395
G1 E-.7 F3600
;WIPE_START
M73 P48 R0
G1 F6240
G1 X87.075 Y90.653 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X85.819 Y87.872 F7800
G1 E1 F2400
;TYPE:External perimeter
G1 F900
G1 X92.009 Y94.483 E1.68062
G1 X85.819 Y94.483 E1.14879
M73 P50 R0
G1 X85.819 Y88.022 E1.19885
M73 P51 R0
G1 X84.845 Y88.099 F7800
M73 P52 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X86.178 Y88.398 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X87.541 Y93.322 F7800
G1 E1 F2400
;TYPE:Solid infill
;WIDTH:1.0215
G1 F900
G1 X88.182 Y92.681 E.17229
G1 X87.556 Y92.014 E.17383
M73 P53 R0
G1 X86.979 Y92.591 E.15518
;LAYER_CHANGE
;Z:1.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;1.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X87.347 Y92.223 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z1.35 F7800
;AFTER_LAYER_CHANGE
;1.35
G1 X86.854 Y91.368
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1.28537
G1 F900
M73 P54 R0
G1 X88.802 Y93.447 E.69778
G1 X86.854 Y93.447 E.47697
G1 X86.854 Y91.518 E.47257
G1 E-.7 F3600
;WIPE_START
M73 P55 R0
G1 F6240
G1 X87.223 Y91.884 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X85.819 Y88.747 F7800
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X91.19 Y94.483 E1.45817
G1 X85.819 Y94.483 E.99674
M73 P56 R0
G1 X85.819 Y88.897 E1.03649
M73 P57 R0
G1 X84.845 Y88.974 F7800
;LAYER_CHANGE
;Z:1.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;1.85


M73 P58 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X86.179 Y89.272 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z1.85 F7800
;AFTER_LAYER_CHANGE
;1.85
G1 X86.73 Y91.929
M73 P59 R0
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1.03756
G1 F900
G1 X88.268 Y93.571 E.43509
G1 X86.73 Y93.571 E.29741
G1 X86.73 Y92.079 E.28857
M73 P60 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X87.103 Y92.441 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X85.819 Y89.622 F7800
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X90.37 Y94.483 E1.23572
G1 X85.819 Y94.483 E.84468
M73 P61 R0
G1 X85.819 Y89.772 E.87412
M73 P62 R0
G1 X84.845 Y89.849 F7800
;LAYER_CHANGE
;Z:2.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;2.35


M73 P63 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X86.18 Y90.146 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z2.35 F7800
;AFTER_LAYER_CHANGE
;2.35
G1 X85.819 Y90.497
G1 E1 F2400
G1 F900
M73 P64 R0
G1 X89.551 Y94.483 E1.01328
G1 X85.819 Y94.483 E.69263
G1 X85.819 Y90.647 E.71176
M73 P65 R0
G1 X84.845 Y90.724 F7800
G1 E-.7 F3600
;WIPE_START
M73 P66 R0
G1 F6240
G1 X86.181 Y91.02 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X87.118 Y93.354 F7800
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:1.47219
G1 F900
G1 X87.033 Y93.502 E.04841
G1 X86.862 Y93.502 E.04841
G1 X86.777 Y93.354 E.04841
G1 X86.862 Y93.206 E.04841
G1 X87.033 Y93.206 E.04841
;LAYER_CHANGE
;Z:2.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;2.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
M73 P67 R0
G1 X86.862 Y93.206 E-.09351
G1 X86.777 Y93.354 E-.09351
G1 X86.862 Y93.502 E-.09351
G1 X86.87 Y93.502 E-.00448
;WIPE_END
G1 E-.015 F3600
G1 Z2.85 F7800
;AFTER_LAYER_CHANGE
;2.85
G1 X85.819 Y91.372
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:1
G1 F900
G1 X88.732 Y94.483 E.79083
G1 X85.819 Y94.483 E.54057
M73 P68 R0
G1 X85.819 Y91.522 E.54939
G1 X84.845 Y91.599 F7800
M73 P69 R0
G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X86.183 Y91.893 E-.285
;WIPE_END
G1 E-.015 F3600
G1 X86.808 Y93.602 F7800
G1 E1 F2400
;TYPE:Perimeter
;WIDTH:0.976577
G1 F900
G1 X86.754 Y93.696 E.01963
G1 X86.645 Y93.696 E.01963
M73 P70 R0
G1 X86.591 Y93.602 E.01963
G1 X86.645 Y93.508 E.01963
G1 X86.754 Y93.508 E.01963
;LAYER_CHANGE
;Z:3.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;3.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X86.645 Y93.508 E-.05955
G1 X86.591 Y93.602 E-.05955
G1 X86.645 Y93.696 E-.05955
G1 X86.754 Y93.696 E-.05955
G1 X86.797 Y93.622 E-.04679
;WIPE_END
G1 E-.015 F3600
G1 Z3.35 F7800
;AFTER_LAYER_CHANGE
;3.35
G1 X85.912 Y92.484
G1 E1 F2400
;TYPE:External perimeter
;WIDTH:1.18683
G1 F900
G1 X87.697 Y94.389 E.58593
G1 X85.912 Y94.389 E.40051
M73 P71 R0
G1 X85.912 Y92.634 E.39401
G1 X84.938 Y92.711 F7800
;LAYER_CHANGE
;Z:3.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;3.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
M73 P72 R0
G1 X86.283 Y92.998 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z3.85 F7800
;AFTER_LAYER_CHANGE
;3.85
G1 X85.788 Y93.045
G1 E1 F2400
;WIDTH:0.939021
G1 F900
G1 X87.163 Y94.513 E.3478
G1 X85.788 Y94.513 E.23774
G1 X85.788 Y93.195 E.22793
M73 P73 R0
G1 X84.814 Y93.272 F7800
;LAYER_CHANGE
;Z:4.35
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;4.35


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X86.163 Y93.555 E-.285
;WIPE_END
G1 E-.015 F3600
G1 Z4.35 F7800
;AFTER_LAYER_CHANGE
;4.35
G1 X86.102 Y94.345
M73 P74 R0
G1 E1 F2400
;WIDTH:1.27512
G1 F900
G1 X86.029 Y94.472 E.03544
G1 X85.883 Y94.472 E.03544
G1 X85.81 Y94.345 E.03544
G1 X85.883 Y94.219 E.03544
G1 X86.029 Y94.219 E.03544
;LAYER_CHANGE
;Z:4.85
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0
;4.85


G1 E-.7 F3600
;WIPE_START
G1 F6240
G1 X85.883 Y94.219 E-.08001
G1 X85.81 Y94.345 E-.08001
G1 X85.883 Y94.472 E-.08001
G1 X85.965 Y94.472 E-.04498
;WIPE_END
G1 E-.015 F3600
G1 Z4.85 F7800
;AFTER_LAYER_CHANGE
;4.85
G1 X85.815 Y94.593
G1 E1 F2400
;WIDTH:0.957301
G1 F900
M73 P75 R0
G1 X85.761 Y94.685 E.01877
G1 X85.655 Y94.685 E.01877
G1 X85.602 Y94.593 E.01877
G1 X85.655 Y94.501 E.01877
G1 X85.761 Y94.501 E.01877
G1 E-.7 F3600
;WIPE_START
G1 F6240;_WIPE
G1 X85.655 Y94.501 E-.05823
G1 F6240;_WIPE
G1 X85.602 Y94.593 E-.05823
G1 F6240;_WIPE
G1 X85.655 Y94.685 E-.05823
G1 F6240;_WIPE
G1 X85.761 Y94.685 E-.05823
G1 F6240;_WIPE
G1 X85.809 Y94.603 E-.05207
;WIPE_END
G1 E-.015 F3600
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G1 Z6.85 F600 ; Move print head up
G1 X5 Y144 F7800 ; present print
G1 Z74.85 F600 ; Move print head further up
M73 P77 R0
G1 Z108 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84 X Y E ; disable motors
M73 P100 R0
; filament used [mm] = 28.33
; filament used [cm3] = 0.07
; filament used [g] = 0.08
; filament cost = 0.00
; total filament used [g] = 0.08
; total filament cost = 0.00
; estimated printing time (normal mode) = 46s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0\n;{layer_z}\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = ;printer_notes=~/.*PRINTER_VENDOR_KINGROON.*/
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "PLA @KP3S"
; default_print_profile = 0.16mm @KP3S
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.8} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84 X Y E ; disable motors
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 1
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #DDDDDD
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 10
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "PLA @KP3S - Copy"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 5%
; fill_pattern = 3dhoneycomb
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 120%
; first_layer_height = 0.35
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = ;"PLA @KP3S";KP3S
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;{layer_z}
; layer_height = 0.5
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 500
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 500
; machine_max_acceleration_y = 500
; machine_max_acceleration_z = 100
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 10
; machine_max_jerk_e = 5
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.75
; max_print_height = 180
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.1
; min_print_speed = 15
; min_skirt_length = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 1
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = 
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 2
; physical_printer_settings_id = KP3S01
; post_process = 
; print_settings_id = KP3S Custom
; printer_model = KP3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_KINGROON\nPRINTER_MODEL_KP3S\n
; printer_settings_id = KP3S - 1.0mm
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 1
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 60
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM140 S{first_layer_bed_temperature[0]} ; set final bed temp\nM104 S150 ; set temporary nozzle temp to prevent oozing during homing and auto bed leveling\nG4 S10 ; allow partial nozzle warmup\nG28 ; home all axisG1 Z50 F240\nG1 X7.6 Y10 F3000\nM104 S{first_layer_temperature[0]} ; set final nozzle temp\nM190 S{first_layer_bed_temperature[0]} ; wait for bed temp to stabilize\nM109 S{first_layer_temperature[0]} ; wait for nozzle temp to stabilize\nG1 Z0.28 F240\nG92 E0\nG1 Y140 E10 F1500 ; prime the nozzle\nG1 X4 F5000\nG92 E0\nG1 Y10 E10 F1200 ; prime the nozzle\nG92 E0
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 20
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 205
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 12
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
